### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 10: invalid continuation byte

### ISSUE THREAD

**Issue by Pravithaks** [AlexandrovLab/SigProfilerMatrixGenerator#100]
Hello Team,
When I tried to create matrix I received this error. Please let me know how to rectify this. I will share the error here.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mvrccri/miniconda3/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 363, in SigProfilerMatrixGeneratorFunc
    snv, indel, skipped, samples = convertIn.convertVCF(project, vcf_path, genome, output_path, ncbi_chrom, log_file)
  File "/home/mvrccri/miniconda3/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/convert_input_to_simple_files.py", line 57, in convertVCF
    for lines in f:
  File "/home/mvrccri/miniconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 10: invalid continuation byte

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @Pravithaks,

Could you please share the command that you ran?

Also, please verify that your input file is properly formatted. Example here:
https://osf.io/8vm4p

**Comment by Pravithaks** [comment]
Hai @mdbarnesUCSD,
 >>>from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
>>> matrices = matGen.SigProfilerMatrixGeneratorFunc("test", "mm39", "/home/mvrccri/Desktop/sig/",plot=True, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)
The above are the commands I ran.

**Comment by mdbarnesUCSD** [comment]
Saving your file with other programs (ie Excel) may modify the encoding and can cause issues when reading it in. Please try encoding your input file as utf-8 or saving as plain text.

**Comment by Pravithaks** [comment]
I will try. I want to inform you that Dr. Anu R I (Boss) has already sent the vcf file to Dr. Ludmil few days back.

**Comment by mdbarnesUCSD** [comment]
Yes, vcf files do work as detailed on the README.

> INPUT FILE FORMAT
> 
> This tool currently supports maf, vcf, simple text file, and ICGC formats. The user must provide variant data adhering to one of these four formats. If the user’s files are in vcf format, each sample must be saved as a separate file.

Test vcf files are at [/SigProfilerMatrixGenerator/SigProfilerMatrixGenerator/references/vcf_files/](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/tree/master/SigProfilerMatrixGenerator/references/vcf_files).

**Comment by Pravithaks** [comment]
Could you tell me what does it mean by each column of the VCF file. How they are arranged. so that I could change my VCF file like this. 

X	13784084	PD11326a	A	T	.	Simulations	mm9	CAT	-1

I'm just curious to know that if I change my VCF file into the above screenshot format, is that possible to run. I'm just confused which format should I follow for VCF file to  run this tool. Please give a clarify on this.

**Comment by mdbarnesUCSD** [comment]
Please read more about [samtools](https://samtools.github.io/hts-specs/VCFv4.2.pdf).

**Comment by Pravithaks** [comment]
Hai @mdbarnesUCSD,

I tried to save my input vcf file as plain text. Still it shows file format not supported. Please let me about this.
