### ISSUE TITLE
Decouple reference file installation from python-site installation

### ISSUE THREAD

**Issue by skchronicles** [AlexandrovLab/SigProfilerMatrixGenerator#101]
Hello there,

I just wanted to start this off by saying thank you for creating and maintaining this awesome tool!

I have a few questions related to installing reference files for SigProfilerMatrixGenerator. In the documentation, it mentions that you can point to a directory containing a tarball of the reference genome. I was just wondering if it would also be possible to define another location for installing the reference files. I check very quickly, and right now, it appears to be downloading the reference file in a location relative it the python package site installation:
![image](https://user-images.githubusercontent.com/18038345/183747259-97aaa36d-9134-4629-80e3-8e706834a021.png)
![image](https://user-images.githubusercontent.com/18038345/183747729-4dce21d7-1543-4264-bcb4-55bed553e776.png)

The reference directory grew from 144M to 1.3G after installing GRCh38.

If it wouldn't be too much work, would it be possible to allow the user to select a directory where these reference files should be downloaded? I bring this up because I am building a [docker image for this tool](https://hub.docker.com/repository/docker/skchronicles/ncbr_sigprofiler) so we can incorporate it into a pipeline. It would be great if I could build the image without the reference files in the container (this makes the size of the docker image much larger than it should be). This also become problematic when building an image that support multiple genomes, or if you want to support an new genome (you will need to rebuild the image).

If you don't have time for this, I understand. This is pretty low priority in the grand scheme of things. 
Please let me know what you think, and if this is already possible. 

Best Regards,
Skyler Kuhn

**Comment by mdbarnesUCSD** [comment]
Thanks for your interest in our tools @skchronicles. You are correct, the reference genomes are installed in the python package site installation. Unfortunately though, at this time, we will not be adding support for a custom installation path for reference genomes.

**Comment by skchronicles** [comment]
@mdbarnesUCSD 

I understand. Thank you for looking into this in more detail. Please let me know if you change your mind.

Best Regards,
@skchronicles
