### ISSUE TITLE
Why are samples with only deletion SVs removed when generating SV matrix via SVMatrixGenerator.py script?

### ISSUE THREAD

**Issue by esavage111** [AlexandrovLab/SigProfilerMatrixGenerator#103]
When using BRASS SV call data for 175 samples as input to SVMatrixGenerator.py script (using "hard-coded" insertion, tandem-deletion, etc. SV class or strand1/strand2 input), samples with only deletion SVs (no other type of SV) are removed from output matrix. Why are these samples being removed and where in the  SVMatrixGenerator.py script is this happening?

**Comment by esavage111** [comment]
After taking a closer look at the script it appears these samples are being removed due to only having deletions that are < 1 kb in length: 

`to_remove = []
    #remove SV's less than 1KB (unless its a translocation)
    for row in df.itertuples():
        index = row.Index
        if row.svclass != "translocation" and row.length < 1000:
            to_remove.append(index)
            #print(row)

    df.drop(df.index[to_remove], inplace=True)
    return df`

Perhaps including a brief bullet point/warning in README under SV matrix section would help to disambiguate this issue.

**Comment by azhark2** [comment]
The smallest size bin of the SV classification is 1kb-10kb. Hence, SVs that are <1KB are not considered, and samples only having deletions that are < 1 kb in length will be removed (as they should).
