### ISSUE TITLE
How to process copy number segment from PICNIC

### ISSUE THREAD

**Issue by KKAres** [AlexandrovLab/SigProfilerMatrixGenerator#107]
recently I download the copy number segment from https://cancer.sanger.ac.uk/cell_lines/download. But the data comes from the file type PICNIC which you  did not provide. So I would like to know if such data can be processed with your pipeline. Looking forward your answers~

**Comment by azhark2** [comment]
Hi, sorry for the delayed response, would be happy to add support for PICNIC data. Can you please email me some example data (akhandek@eng.ucsd.edu) as I cannot access the data at the link you provided because I do not have a COSMIC account.
