### ISSUE TITLE
input file 

### ISSUE THREAD

**Issue by ruinw** [AlexandrovLab/SigProfilerMatrixGenerator#108]
My maf file is output of maftools in R which is output file by ANNOVAR that is a txt file with all samples.When i use this maf as inputfile,there be "The given input files do not appear to be in the correct MAF format. Skipping this file:  SigNature.maf"

python3
>>>from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
>>>matrices = matGen.SigProfilerMatrixGeneratorFunc("SigNature", "GRCh38", "/home/data/t170306/mutation/SigNature",plot=True, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)
The given input files do not appear to be in the correct MAF format. Skipping this file:  SigNature.maf
Starting matrix generation for SNVs and DINUCs...

**Comment by mdbarnesUCSD** [comment]
Hi @ruinw,

Thanks for reaching out. Could you please check that your format matches the [example maf file on the wiki page](https://osf.io/dkjwr)?

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please re-open this issue if the problem persists.
