### ISSUE TITLE
What is the input format of the copy number segment data of ABSOLUTE?

### ISSUE THREAD

**Issue by KKFFCC** [AlexandrovLab/SigProfilerMatrixGenerator#110]
The output of my ABSOLUTE is like this

![image](https://user-images.githubusercontent.com/31646098/199948765-bcbbbd87-25f9-4949-892d-4d62561790d4.png)
sample	Chromosome	Start.bp	End.bp	n_probes	length	seg_sigma	W	total_copy_ratio
But when generating features, what is the reason for the following error?

![image](https://user-images.githubusercontent.com/31646098/199951086-8e843109-b40e-44dc-a4c4-7f5d3dd8ca4c.png)
I hope you can help me understand, what input format should I handle?

**Comment by azhark2** [comment]
Hi, sorry for the delayed response, please see this link:

https://www.genepattern.org/analyzing-absolute-data#gsc.tab=0

An example file with the columns required can be found here:

https://www.synapse.org/#!Synapse:syn1710464.1
