### ISSUE TITLE
VCF input list

### ISSUE THREAD

**Issue by SteeleCD** [AlexandrovLab/SigProfilerMatrixGenerator#111]
Currently for a VCF input, all VCFs must be in the same folder. Would it be possible to hand a file with a list of VCF paths instead? Sometimes VCFs are distributed in multiple places on a file system, and it would be helpful to not have to reproduce them before running matrix generator.

**Comment by mdbarnesUCSD** [comment]
Thanks for your input. It seems that copying VCF files found on a list of paths to a common location versus supplying a file with a list of paths are similar tasks. For now the task of copying VCF files to a common location will reside with the user.
