### ISSUE TITLE
Will the largest tumour cell fraction be selected when 'BATTENBERG' segmentation file is supplied? 

### ISSUE THREAD

**Issue by aliahhawari** [AlexandrovLab/SigProfilerMatrixGenerator#119]
Hi, I would just like to ask whether the largest tumor cell fraction will be selected if I supply the Battenberg segmentation file for Copy Number Signatures matrix generation. So that NMaj1, NMin1 and NMaj2, NMin2 will be swapped if frac2 > frac1 for example? Thanks.

**Comment by azhark2** [comment]
If there are multiple clones with different copy number states, all of them will be considered when generating the matrix. So both the larger cell fraction and smaller cell fraction solutions will be classified and counted.
