### ISSUE TITLE
exome=True label

### ISSUE THREAD

**Issue by britneyting** [AlexandrovLab/SigProfilerMatrixGenerator#120]
Hi, the documentation for the "exome" flag states that if "exome=True", the matrix generator will "Downsample mutational matrices to the exome regions of the genome". If we are already using exome data, should we set this flag to True or False? I tried both and used SigProfilerExtractor, and it seems like the different signatures are extracted for each case, so not sure which flag to use.

**Comment by mdbarnesUCSD** [comment]
Hi @britneyting,

You will want to set exome=True for running SigProfilerExtractor with exome data.

Thanks!
