### ISSUE TITLE
Install geno problem,Help!

### ISSUE THREAD

**Issue by Glies2** [AlexandrovLab/SigProfilerMatrixGenerator#121]
When I trying to install("WBcel235",rsync=FALSE, bash=FALSE),
the result is
"Beginning installation. This may take up to 40 minutes to complete.
The ensembl ftp site is not currently responding.
Error in py_call_impl(callable, dots$args, dots$keywords) : SystemExit"
What should I do?
Award for your reply.

**Comment by mdbarnesUCSD** [comment]
Hi @Glies2,

Please use "c_elegans" as the name. Example code below.

```
from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('c_elegans', rsync=False, bash=True)
```

Thanks!

**Comment by Glies2** [comment]
It is kind of you to offer sulotion, It seems that I come across a new problem.Here is the code of the problem.
> install('c_elegans', rsync=False, bash=True)
+ "C:/Users/66421/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--prefix" "C:/Users/66421/AppData/Local/r-miniconda/envs/r-reticulate" "python=3.8" "numpy" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... failed

CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

Error: Error creating conda environment 'C:/Users/66421/AppData/Local/r-miniconda/envs/r-reticulate' [exit code 1]

What should I do?
Looking forward to your reply.

**Comment by Glies2** [comment]
When I run "from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('c_elegans', rsync=False, bash=True)",it comes "tar: Error opening archive: Failed to open 'C:\Users\66421\AppData\Local\Programs\Python\Python311\Lib\site-packages\sigprofilermatrixgenerator-1.2.13-py3.11.egg\SigProfilerMatrixGenerator/references/chromosomes/tsb/c_elegans.tar.gz'
The ensembl ftp site is not currently responding."
Is is the firewall problem?

**Comment by mdbarnesUCSD** [comment]
Yes, you will need to be able to connect to the ftp server and if your firewall is blocking the connection then that can be an issue. Rsync can help with this.
