### ISSUE TITLE
SigProfilerMatrixGeneratorR Genome download problem&rsync issue

### ISSUE THREAD

**Issue by Glies2** [AlexandrovLab/SigProfilerMatrixGenerator#122]
When I trying to “install("c_elegans",rsync=FALSE, bash=FALSE)”,
the result is
"Beginning installation. This may take up to 40 minutes to complete.
The ensembl ftp site is not currently responding.
Error in py_call_impl(callable, dots$args, dots$keywords) : SystemExit"
I do not know what is"Error in py_call_impl(callable, dots$args, dots$keywords) : SystemExit" mean?
By the way, I was run the code in Rstudio.
The question is how to load rysnc in my Windons system?Though you guys had give me some advice.
Please Help me!

**Comment by mdbarnesUCSD** [comment]
Hi @Glies2,

You will need to look into installing this for your own system. The [osf wiki tutorial](https://osf.io/s93d5/wiki/2.%20Installation%20-%20R/) has a link to the [wget page](https://www.gnu.org/software/wget/), which may help you get started.
