### ISSUE TITLE
Working with yeast genome

### ISSUE THREAD

**Issue by DKundnani** [AlexandrovLab/SigProfilerMatrixGenerator#124]
What's the best way to work with Saccharomyces cerevisiae genome? I can see the code has some information about a yeast genome, but I am not able to figure out how can I install the genome without getting errors for transcript regions not being present.

**Comment by mdbarnesUCSD** [comment]
Hi @DKundnani,

Please update SigProfilerMatrixGenerator to v1.2.14 and please do reach out if you encounter any more issues.

Thanks!

**Comment by DKundnani** [comment]
❤️
