### ISSUE TITLE
Annotate VCF with mutation classification

### ISSUE THREAD

**Issue by williambrandler** [AlexandrovLab/SigProfilerMatrixGenerator#126]
SigProfilerMatrixGenerator outputs aggregate information about the numbers of each class of small mutational event in a VCF (e.g. trinucleotide context for SNPs, homopolymer length for indels, doublet substitutions etc.)

I am interested in annotating individual variants from a VCF with these classifications

Is there a way to do this with SigProfilerMatrixGenerator?

If I could easily annotate VCFs I could then build a classifier to filter artifacts in next-generation sequencing data by training on a panel of normals. In normals I am seeing a common 'mutational signature' for artifacts

**Comment by marcos-diazg** [comment]
Dear @williambrandler,

Thanks for reaching out. Please run SigProfilerMatrixGenerator using `seqInfo=True` and check your `vcf_files` directory in the output folder.
