### ISSUE TITLE
reference files corrupted

### ISSUE THREAD

**Issue by sbg-dalibor** [AlexandrovLab/SigProfilerMatrixGenerator#13]
Hello,

after SigProfilerMatrixGenerator is installed, when i try to install 'GRCh38' or 'GRCh37' , installation process fails and i get message that 'files may be corrupted' and 'to try to reinstall genomes'. I reinstalled genomes multiple times but result is always the same. What should i do to resolve this issue?

Note: i tried installing genomes in the way that is explained in readme on github page.

Best regards,
Dalibor

**Comment by ebergstr** [comment]
Hi Dalibor,

This is most likely caused by interruptions or incomplete downloads of the reference genome. What operating system are you using? Do you have internet connection from your machine?

Best,
Erik

**Comment by sbg-dalibor** [comment]
Hello, thank you for quick response!

I am using mac os, and i have good internet connection.

Some additional info regarding my problem:

I am using newest version of wget and rsync, i tried downloading with and without rsync .

Reference files are downloaded to(for GRCh37) : /Users/my_user_name/anaconda3/envs/MS_36_exp/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/chrom_string/GRCh37. Following reference files are downloaded and they take more than 3gb of disk space:
1.txt,	12.txt,	15.txt,	18.txt,	20.txt,	3.txt,	6.txt,	9.txt	,Y.txt,
10.txt,	13.txt,	16.txt,	19.txt,	21.txt,	4.txt	, 7.txt,	MT.txt,
11.txt,	14.txt,	17.txt,	2.txt,	22.txt	5.txt	,8.txt,	X.txt

After files are downloaded i always get   'corrupted files message' due to unsuccessful checksum check.

Maybe i should try downloading those files manually, Is there a way to do that?

**Comment by sbg-dalibor** [comment]
I tried running the program on other computer and everything worked. It seems that errors happened duo to my machine setups.

Thank you for helping!

Best regards,
Dalibor
