### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Dhwani-2410** [AlexandrovLab/SigProfilerMatrixGenerator#130]
I installed SigProfilerMatrixGeneratorR and then tried to load the genome file. But it fails using both Python and R. here is the code for both:
```
library("devtools")
library("reticulate")  
library("SigProfilerMatrixGeneratorR")
use_python(python = "/usr/bin/python3.8")
py_config()



install('GRCh37', rsync=TRUE, bash=TRUE)
beginning installation. This may take up to 40 minutes to complete.
**Direct download for RSYNC is not yet supported**
```
For python:
```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('GRCh37', rsync=True, bash=True)
Beginning installation. This may take up to 40 minutes to complete.
**Direct download for RSYNC is not yet supported**

```

**Comment by mdbarnesUCSD** [comment]
Hi @Dhwani-2410,

Could you please confirm that you have RSYNC installed? If you are not installing from behind a firewall, please try with rsync=false.

Thanks!

**Comment by Dhwani-2410** [comment]
> Hi @Dhwani-2410,
> 
> Could you please confirm that you have RSYNC installed? If you are not installing from behind a firewall, please try with rsync=false.
> 
> Thanks!

**Comment by Dhwani-2410** [comment]
@mdbarnesUCSD 
Yes. RSYNC is installed

```
dhwani@dhwani:~$ rsync
rsync  version 3.1.3  protocol version 31
Copyright (C) 1996-2018 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

**Comment by mdbarnesUCSD** [comment]
If you have access to wget, you can download the genome (or one of the supported genomes on the README) by running:

```bash
wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz

```
Then using python:
```python3
from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('GRCh37', offline_files_path='path/to/directory/containing/GRCh37.tar.gz')
```

**Comment by mdbarnesUCSD** [comment]
Please re-open if you are continuing to encounter this issue.

**Comment by RoniHaas** [comment]
> If you have access to wget, you can download the genome (or one of the supported genomes on the README) by running:
> 
> ```shell
> wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz
> ```
> 
> Then using python:
> 
> ```python
> from SigProfilerMatrixGenerator import install as genInstall
> genInstall.install('GRCh37', offline_files_path='path/to/directory/containing/GRCh37.tar.gz')
> ```


Hello @mdbarnesUCSD , I have a problem installing the reference genome:

When I use wget:
```
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... connected.
Error in server response. Closing.
Retrying.
```

I also cannot install using:
`genInstall.install('GRCh38', rsync=False, bash=True)
`
It says that:
```
The ensembl ftp site is not currently responding.
```

Could you please help with that?
Thank you!

**Comment by mdbarnesUCSD** [comment]
Hi @RoniHaas,


Are you downloading from behind a firewall? If so, then please try with rsync=True.

**Comment by RoniHaas** [comment]
> Hi @RoniHaas,
> 
> Are you downloading from behind a firewall? If so, then please try with rsync=True.

I don't know what the problem was yesterday, but today the same command works for me:
```
genInstall.install('GRCh38', rsync=False, bash=True) 
```
I was able to run the analysis successfully.
Thank you for the help!
