### ISSUE TITLE
SV matrix generation

### ISSUE THREAD

**Issue by pushpa-itagi** [AlexandrovLab/SigProfilerMatrixGenerator#132]
Hi,

I am looking into using the SV matrix generator feature, but I am not clear about the distinction between clustered vs non-clustered based on the sizes. I couldn't find it in the paper, can you please explain what these terms imply? if it is the breakpoints what are the cutoffs to consider it as a cluster.

Thanks

Pushpa

**Comment by azhark2** [comment]
First, SV's are binned according to size and event type. Next, we determine if the individual breakpoints of these SV events are clustered or non-clustered by using piecewise constant fitting algorithm to segment the genome based on the inter-mutational distance(IMD) of these breakpoints to each other. We then compute the average IMD in each segment. If this average is 10X less than the average IMD of all the breakpoints in the sample, we classify all the breakpoints in this segment as clustered. Feel free to follow up if this doesn't make sense or you need additional information, thanks!

**Comment by pushpa-itagi** [comment]
Hi Azhar,

Thank you so much for the quick reply and information, this helps. I will write back if I don’t understand it after running it on the data.

Thanks

Regards,
Pushpa Itagi

From: Azhar Khandekar ***@***.***>
Date: Thursday, March 30, 2023 at 10:29 AM
To: AlexandrovLab/SigProfilerMatrixGenerator ***@***.***>
Cc: Itagi, Pushpa ***@***.***>, Author ***@***.***>
Subject: Re: [AlexandrovLab/SigProfilerMatrixGenerator] SV matrix generation (Issue #132)

First, SV's are binned according to size and event type. Next, we determine if the individual breakpoints of these SV events are clustered or non-clustered by using piecewise constant fitting algorithm to segment the genome based on the inter-mutational distance(IMD) of these breakpoints to each other. We then compute the average IMD in each segment. If this average is 10X less than the average IMD of all the breakpoints in the sample, we classify all the breakpoints in this segment as clustered. Feel free to follow up if this doesn't make sense or you need additional information, thanks!
