### ISSUE TITLE
The transcriptional reference data appears to be corrupted

### ISSUE THREAD

**Issue by brucewu1996** [AlexandrovLab/SigProfilerMatrixGenerator#14]
Hello,
i finished SigProfilerMatrixGenerator install,and i try to install 'GRCh37' reference genome by this command `genInstall.install('GRCh37', rsync=True, bash=True)` . I have been reinstall several times,but always got an error message like `The transcriptional reference data appears to be corrupted. Please reinstall the GRCh37 genome.`  What should i do to resolve this issue?

Operating system is centos 7
Python3.6.2
rsync-3.1.2-6.el7_6.1.x86_64

Best regards,
Bruce

**Comment by ebergstr** [comment]
Hi Bruce,

Thank you for pointing this issue out! We are working on implementing an ftp site for direct download of the reference files to avoid this potential issue. For the time being, we have uploaded the reference files to a google drive: (https://drive.google.com/drive/folders/1f62KhUjhJiSXsso4eEW_oUByIana20pR)

You can download and unzip these files into the following path (the path is referenced to the location of your python packages):
../python/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/

Best,
Erik

**Comment by itsvenu** [comment]
Hi @ebergstr,

sorry for opening this issue again. Would you please provide the access to reference files (thatikonda92@gmail.com)?

I also see this problem.
