### ISSUE TITLE
Assumption for header for BED files in save_context_distribution.py

### ISSUE THREAD

**Issue by danielanach** [AlexandrovLab/SigProfilerMatrixGenerator#140]
After finding some number discrepancies in counting trinucleotide contexts using [save_context_distribution.py](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/c3139c77ee315dc65b5c59b656c410eb440732e5/SigProfilerMatrixGenerator/scripts/save_context_distribution.py), I think I found the source, which is a header-assumption for the input BED files.

Currently, `context_distribution_BED()` skips the first line of the provided BED file. [This is the portion of the code](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/c3139c77ee315dc65b5c59b656c410eb440732e5/SigProfilerMatrixGenerator/scripts/save_context_distribution.py#L307-L447) I am referencing.

This works fine for BED files with a header, but for cases where there is no header, it skips the first listed region. As the header is optional for[ BED format](https://useast.ensembl.org/info/website/upload/bed.html) this skipping should likely only be performed if the presence of a header is confirmed.

**Comment by mdbarnesUCSD** [comment]
Thanks @danielanach, for now we will update the documentation to make it explicit that BED files require a header line. If you come up with a better solution, please feel free to open a pull request.
