### ISSUE TITLE
Serious installation issues

### ISSUE THREAD

**Issue by nurmians** [AlexandrovLab/SigProfilerMatrixGenerator#146]
I spent many hours trying to run the algorithm. Here are some notes for anyone trying to do the same.

**Setup**:
Required Python version >= 3.8
Use `python3.8 -m pip install SigProfilerMatrixGenerator` to install the algorithm and dependencies and to make sure you're downloading correct versions, if you have multiple versions installed. The SigProfilerMatrixGenerator sources will be available under `/usr/local/lib/python3.8/dist-packages/SigProfilerMatrixGenerator` and the refences files need to be placed under `/usr/local/lib/python3.8/dist-packages/SigProfilerMatrixGenerator/references`.

**Reference file download**: Ensemble ftp site download is not working and neither is download from AlexandrovLab.
I got the required files from "https://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/" using wget. This includes all files in format of `'Homo_sapiens.GRCh38.dna.chromosome.1.fa.gz'`. Then I needed to manually wrap them up in a tar.gz package. You might be able to skip this step, the SigProfilerMatrixGenerator just moves them around and unpacks them to `/usr/local/lib/python3.8/dist-packages/SigProfilerMatrixGenerator/references/chromosomes/fasta/GRCh38` (should contain decompressed files such as 'Homo_sapiens.GRCh38.dna.chromosome.1.fa').

**Reference genome installation**: I used `python3.8 SigProfilerMatrixGenerator/install.py --genome GRCh38 --custom` to get the job done. First you have to modify the install.py script and remove the extra "/reference" in the path in variables `chromosome_string_path, transcript_path, output_path.` Also 'S' needs to be capitalized in `os.chdir(first_path + "/SigProfilerMatrixGenerator/")`. 

**Running the algorithm**: Make sure input folder has uncompressed vcf files, or you'll get error "Fileformat not supported". I got the matrices generated using the suggested cmdline `matrices = matGen.SigProfilerMatrixGeneratorFunc("project_test", "GRCh38", "/data/profiler/vcf",plot=True, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)`.

Also check out the nice wiki: https://osf.io/s93d5/wiki/home/

**Comment by mdbarnesUCSD** [comment]
Thanks for documenting your experience. Please reach out in the future if you have any issues connecting to the ftp server or installing one of the supported genomes.

**Comment by nurmians** [comment]
Thanks for fixing it.
