### ISSUE TITLE
Feature request: annotate each variant with the context

### ISSUE THREAD

**Issue by itsvenu** [AlexandrovLab/SigProfilerMatrixGenerator#15]
Hi @ebergstr,

Thanks for the amazing tool. I was just thinking is it possible (with current implementation or with some modifications) to annotate each variant in the input files with the context (for SBS, DBS, ID) and output a text file (may include `chr, position, ref, alt, context, sampleID`).

IMO, there will be several use cases for integrative analysis with this data e.g. one can calculate overrepresentation of different contexts in certain genomic loci such as enhancers or open chromatin regions. 

Any help would be appreciated.

Thank you.

**Comment by ebergstr** [comment]
This is implemented in the seqInfo=True parameter (more information provided on the wiki page
