### ISSUE TITLE
identify SBS4 for tobacco smoking

### ISSUE THREAD

**Issue by Dhwani-2410** [AlexandrovLab/SigProfilerMatrixGenerator#152]
Hello,

I have a VCF file and I would like to know:-
1) Which among the 96SBS is more prominent in the current VCF data based on the classification of SBS by the COSMIC database?
2) Plots of specific SBS4 COSMIC signatures.

These are the commands that i had ran
```
from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
matrices = matGen.SigProfilerMatrixGeneratorFunc("Demo1","GRCh37","/home/dhwani/Desktop/VCFInput/",exome=False, bed_file=None, chrom_based=False, plot=True, tsb_stat=False, seqInfo=True)

from SigProfilerExtractor import sigpro as sig
sig.sigProfilerExtractor("matrix","Demo2","/home/dhwani/Desktop/VCFInput/output/SBS/Demo1.SBS6.all",reference_genome="GRCh37",minimum_signatures=1,maximum_signatures=200,nmf_replicates=100,cpu=-1)
```

In the second command, I want to get SigprofileExtrator only for SBS4(tobacco smoking). But the output from the previous command only consists of SBS6, SBS26, and SBS96.SBS384,SBS1536 and SBS6144

**Comment by mdbarnesUCSD** [comment]
Hi @Dhwani-2410,

To clarify, there is a difference between COSMIC signature SBS4 and the different mutational contexts. Here are resources for each, [COSMIC signatures (ie SBS4](https://cancer.sanger.ac.uk/signatures/sbs/sbs4/)) and [mutational contexts](https://osf.io/s93d5/wiki/5.%20Output%20-%20SBS/).
