### ISSUE TITLE
Duplicated SBS in vcf with 1 mutation?

### ISSUE THREAD

**Issue by maia-munteanu** [AlexandrovLab/SigProfilerMatrixGenerator#153]
Hi!

I've been using the MatrixGenerator on a set of vcf files and I've noticed a rare but weird behaviour. When examining the output file, I notice some mutations are classified as errors and the log files seem to suggest they've been skipped due to being duplicated, e.g. 

> There appears to be a duplicate single base substitution. Skipping this mutation: 18 61459932 A C

The only issue is, that some of these samples have only 1 mutation, the one being skipped. For example, one vcf file is: 

> ##fileformat=VCFv4.2
> #CHROM  POS     ID      REF     ALT     QUAL    FILTER
> 18      61459932        rsX     A       C       .       PASS

So I'm having trouble understanding why this is classed as a duplicated mutation. I have tried to redo the counting on single files and the mutations get counted correctly, so I suspect it has something do to with the mutations in the other samples being counted at the same time. Is MatrixGenerator removing all SNVs that are duplicated between samples, not just within? If so, is there a way to turn this off? 

The consequence of this is that the .all file then includes columns with 0 mutations, which, when used for signature decomposition for instance (with SigProfilerAssignment), generates an error

> ValueError: cannot convert float NaN to integer

Do you have any suggestions for why this might be happening?

Thanks,
Maia

**Comment by mdbarnesUCSD** [comment]
Hi @maia-munteanu,

Thank you for reaching out and providing a detailed explanation of your issue.

To clarify, in SigProfilerMatrixGenerator, a mutation is considered a duplicate and subsequently removed if it shows up more than once within the same sample. However, if the same mutation appears across two different samples, it is not considered a duplicate.

Best,
Mark

**Comment by maia-munteanu** [comment]
Hi Mark,

Thanks a lot for getting back to me so quickly! The parameters are as below:

> matrices = matGen.SigProfilerMatrixGeneratorFunc(project, "GRCh37", output, plot=False, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)

where output is the directory that contains all the vcf files. 

I seem to have 3 samples, all with 1 mutation within the vcf that get skipped because they are marked as duplicates. All other mutation counts are accurate, so I'm really not sure what's causing this behaviour.


Thanks,
Maia

**Comment by mdbarnesUCSD** [comment]
Hi @maia-munteanu,

I tested SigProfilerMatrixGenerator v1.2.17 by generating three different VCFs each with the same single mutation, and the resulting matrix contains three samples with the count for that mutation. Could you please provide inputs and a script to reproduce the run that you are describing? You can e-mail it to me if you'd like (e-mail is at the bottom of the README).

Thanks!

**Comment by maia-munteanu** [comment]
Hi,

I think I've figured out what's going on, but I'm not entirely sure how to solve it. I've left the vcfs files below, I think you will be able to reproduce it.
Basically, Hartwig samples are notated like CPCT02020656**T**, CPCT02020656**TII**, CPCT02020656T**III** when the same patient was sampled multiple times, like the primary and the metastasis site, for example. For this reason - they will share mutations and it seems that the combination of repeating mutations in 2 separate vcfs and the shared patient ID (albeit with a different suffix) somehow interact and the samples with **TII** have those "overlapping" mutations marked as duplicates and removed. In the case where all mutations in that sample overlap with the previous, the outputted counts matrix file (.all) will have a column of 0s, which causes problems down the line. 

The weird this is that, apart from this situation where the mutations are the same, everything gets counted normally - so the sample suffix is sufficient to differentiate between the samples. But when checking for duplicates, it's seen as 1 sample somehow?


Thanks,
Maia


[VCF_files.zip](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/files/12497678/VCF_files.zip)

**Comment by mdbarnesUCSD** [comment]
Hi @maia-munteanu,

It looks like the id column for all of the different samples are the same. Prior to running the matrix generator, modify the ID column value of each VCF to be the sample name or some unique value (ie CPCT02020656T instead of rsx). I believe this should resolve the issue you are encountering.

**Comment by maia-munteanu** [comment]
Hi Mark,

Thanks a lot! This seems to have done the trick.


Maia
