### ISSUE TITLE
not working ftp refererence

### ISSUE THREAD

**Issue by sonyuna90** [AlexandrovLab/SigProfilerMatrixGenerator#154]
Hi, 

I can't download the GRCh37 or GRCh38 reference genome from ftp using wget or GeneInstall. It seems that it has been a while to have this issue and I am wondering if there is a solution for this.

**Comment by mdbarnesUCSD** [comment]
Hi @sonyuna90,

Please refer to posts #79 and #28.

If you are still encountering issues, please reach out.

Thanks!

**Comment by mdbarnesUCSD** [comment]
The recent update has included a status badge for the FTP server on the README. Please reach out if you are still encountering issues with installation.
