### ISSUE TITLE
Unable to download reference genome files

### ISSUE THREAD

**Issue by Xiongshizheng** [AlexandrovLab/SigProfilerMatrixGenerator#155]
I just started trying to deploy the SigProfilerCluster you posted on github, and I got the following error when executing the 
genInstall.install('GRCh37', bash=True) 

**Beginning installation. This may take up to 40 minutes to complete.
??? Linux ? Windows ?????????????
?????? Microsoft Store ??????:
https://aka.ms/wslstore
??? Linux ? Windows ?????????????
?????? Microsoft Store ??????:
https://aka.ms/wslstore
tar: Error opening archive: Failed to open 'D:\Python\Anaconda\envs\sig\Lib\site-packages\SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz'
The ensembl ftp site is not currently responding.**

hoping to get your answer！

**Comment by mdbarnesUCSD** [comment]
Hi @Xiongshizheng,

Please look at #154 and see if this resolves your issue. If you are still having difficulties, please post on that thread. Thanks!
