### ISSUE TITLE
Stale link

### ISSUE THREAD

**Issue by EmreKocakavuk** [AlexandrovLab/SigProfilerMatrixGenerator#16]
Looks like Ensemble is throwing invalid ftp location for GRCh37 links. This should be replaced with the most current GRCh37 at Ensembl (release-75) for all of downloads related to GRCh37: ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/dna/

https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/681a0c33b1b7eb943eb2a1fc8055105c22ee6a92/SigProfilerMatrixGenerator/install.py#L87

**Comment by ebergstr** [comment]
Thank you for pointing this out. We have uploaded our reference files to an ftp site for direct download. This should happen by default now, or you can use the ftp=True parameter in the install function.

**Comment by AndrewPattison** [comment]
Has this been done for rn6? `genInstall.install('rn6', rsync=False, bash=True, ftp=True)` is not working for me but GRCh37 works fine.
