### ISSUE TITLE
CN mutational matrix generation using the SigProfiler Assignment web tool with customized CNV output cancer data

### ISSUE THREAD

**Issue by Jasonmbg** [AlexandrovLab/SigProfilerMatrixGenerator#160]
Dear AlexandrovLab people,

good afternoon and I hope my message reaches you well !! I would like to ask a particular question for the generation of CN signatures implementning the useful SigProfiler Assignment web tool and respective mutational signatures (https://cancer.sanger.ac.uk/signatures/assignment/opt-in/), based on the SigProfilerMatrixGenerator tool : 

in particular, based on a finalized project regarding the identification of actionable mutations at the patient resolution, concerning one “in-house” small colorectal cancer cohort, we have identified two representative example {specific patients} with selected vulnerabilities; On this premise, for publication purposes we would also like to utilize your very nice interface SigProfilerAssignment with the latest databases, to also utilize some of the latest capabilities regarding the copy number variation signature analysis, and see if we could further correlate and utilize with our findings; My main question concerns the input file and the respective format;
 
Regarding our CN pipeline, we utilized a customized version of the cnvkit-ACESeq tools, to provide both total and allele-specific copy numbers (https://www.biorxiv.org/content/10.1101/210807v1); unfortunately, there are not included in any of the available format tools you pinpoint in the Segmentation file format argument; Is there a way to also upload this “customized” format or modify it accordingly for performing successfully the analysis? For simplicity, for one patient I have attached the respective output of the pipeline here;
[ExamplePatient_comb_pro_extra2.03_0.9.withGenes.txt](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/files/13178490/ExamplePatient_comb_pro_extra2.03_0.9.withGenes.txt)

PS1: The TCN column corresponds to the total copy number;

Thank you in advance for your time and consideration on this matter !!

Kind Regards,

Efstathios-Iason

**Comment by azhark2** [comment]
Thanks for reaching out! I have looked over the sample input file you provided, and indeed, it seems it can be easily modified to work with our tool. Can you please indicate which columns contain the copy numbers for each allele?

**Comment by Jasonmbg** [comment]
Dear @azhark2 , thanks a gazillion for your fast and positive reply !! The columns V and W (c1Mean & c2Mean) contain the allele specific copy numbers, but not rounded; Hence, with the necessity of double checking, columns X & Y (named as A and B) essentially contained the "rounded" ones; I hope this information suffices;

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/e376s/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/e376s/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



c1Mean
--




</body>

</html>

**Comment by azhark2** [comment]
In that case, I would rename your "V" and "W" columns as "nMajor" and "nMinor".
Rename your "start" and 'end" columns to "startpos" and "endpos".
Then, run the function with the file_type = "ASCAT".
Let me know if that works!

**Comment by Jasonmbg** [comment]
Dear @azhark2 , thank you very much for your updated reply and feedback !! Two additional comments before proceeding:
1. For the total input, I should concatenate all sample files into 1 final txt file, correct? So the input format as txt/tsv would suffice?
2. You mentioned  "ASCAT", and not "ASCAT_NGS" , correct?

**Comment by azhark2** [comment]
Yes, concatenate into one file, and yes, ASCAT, not ASCAT NGS. I think this is the simplest solution for now, and later, I'll add support for custom segmentation files. Once your tool gets published, I'll add support for that too.
Feel free to open this again if you encounter another issue!

**Comment by Jasonmbg** [comment]
Dear @azhark2 , 

unfortunately I tried to run based on your suggestions but encountered an error:

![Error CN](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/18385144/1dff38c2-797b-47fd-abb7-b77bcf1681f3)

I attach also the concatenated CNV tsv file I used as input;

[Input_CNVs_Mod_SigProfiler.txt](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/files/13206612/Input_CNVs_Mod_SigProfiler.txt)

**Comment by marcos-diazg** [comment]
Hi @Jasonmbg,

Thanks for letting us know! Just change the name of your first column from "file" to "sample" and you will solve this issue.

I hope this helps. Best,

Marcos
