### ISSUE TITLE
Use curl instead of wget?

### ISSUE THREAD

**Issue by mattjmeier** [AlexandrovLab/SigProfilerMatrixGenerator#161]
I am attempting to integrate some of the sigprofiler tools into a workflow that will sometimes be run by Windows users.

The genome install portion depends on `wget`, which is not distributed with Windows by default.

However, `curl` is - would this be a viable alternative?

Thanks!
Matt

**Comment by mattjmeier** [comment]
After looking into this a bit more, I think there may be a bug with the current install.py script that prevents it from working in Windows altogether (at least on any machines I have tried).

```
> SigProfilerMatrixGeneratorR::install('GRCh38', rsync=FALSE, bash=TRUE) 
Beginning installation. This may take up to 40 minutes to complete.
The ensembl ftp site is not currently responding.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
SystemExit
Run `reticulate::py_last_error()` for details.
>   SigProfilerMatrixGeneratorR::install('GRCh38', rsync=TRUE, bash=TRUE)
Beginning installation. This may take up to 40 minutes to complete.
Direct download for RSYNC is not yet supported
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
SystemExit
Run `reticulate::py_last_error()` for details.
```

When I tried this out last year, it did indeed run.

Sorry I'm posting this here instead of the SigProfilerMatrixGeneratorR package, but I think the issue is with the code here, not the R package.

I also tried to figure out a method for downloading from the ftp site manually, and placing into the `references/chromosomes/tsb`  folder (as alluded to in #131 I believe), but couldn't get it to install that way either - any advice on how to use that?

Finally, what is meant exactly by the `custom` True/False? Is this whether to install in a custom directory, or use a custom genome? Either way - I cannot currently get any reference genomes to install on Windows using these methods.

**Comment by mattjmeier** [comment]
OK: I noticed that, most likely, bash must be set to `false` for Windows installs. That makes sense (you might want to document this somewhere for people like me who don't pay close enough attention).

However, this is still a problem, from install.log: (file path redacted)

```
805200K .......... .......... ..........                      100% 4.79M=17m9s

2023-11-02 15:55:37 (782 KB/s) - 'C:/NNNNNN/GRCh38.tar.gz' saved [824556503]

FINISHED --2023-11-02 15:55:37--
Total wall clock time: 17m 13s
Downloaded: 1 files, 786M in 17m 9s (782 KB/s)
```

Then it fails after that with:

```
>   SigProfilerMatrixGeneratorR::install("GRCh38", rsync=FALSE, bash=FALSE)
Beginning installation. This may take up to 40 minutes to complete.
The ensembl ftp site is not currently responding.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
SystemExit
Run `reticulate::py_last_error()` for details.
```

And the more details from `py_last_error()` :

```
Traceback (most recent call last):
  File "C:\NNNNNNN\VIRTUA~1\R-RETI~1\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 907, in install
    os.remove(str(reference_dir.get_tsb_dir() / genome) + ".tar.gz")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\NNNNNNN\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\SigProfilerMatrixGenerator\\references\\chromosomes\\tsb\\GRCh38.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\NNNNNNN\VIRTUA~1\R-RETI~1\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 910, in install
    sys.exit()
SystemExit

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─genInstall$install(genome, custom, rsync, bash, ftp)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 ```

**Comment by mdbarnesUCSD** [comment]
Hi @mattjmeier,

Thanks for reaching out and providing detailed information. The parameter rsync should be set to TRUE and and bash to FALSE when downloading on windows. It looks from this installation command that was run that it downloaded successfully:

> 805200K .......... .......... ..........                      100% 4.79M=17m9s
> 
> 2023-11-02 15:55:37 (782 KB/s) - 'C:/NNNNNN/GRCh38.tar.gz' saved [824556503]
> 
> FINISHED --2023-11-02 15:55:37--
> Total wall clock time: 17m 13s
> Downloaded: 1 files, 786M in 17m 9s (782 KB/s)

Then it looks from this run, that there was an unsuccessful attempt to download GRCh38 (with rsync set to False):

> SigProfilerMatrixGeneratorR::install("GRCh38", rsync=FALSE, bash=FALSE)
> Beginning installation. This may take up to 40 minutes to complete.
> The ensembl ftp site is not currently responding.
> Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
> SystemExit
> Run `reticulate::py_last_error()` for details.

The py_last_error() message looks like after it tried to install without RSYNC, it failed and attempted to remove the file (which was not present):

> Traceback (most recent call last):
>   File "C:\NNNNNNN\VIRTUA~1\R-RETI~1\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 907, in install
>     os.remove(str(reference_dir.get_tsb_dir() / genome) + ".tar.gz")
> FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\NNNNNNN\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\SigProfilerMatrixGenerator\\references\\chromosomes\\tsb\\GRCh38.tar.gz'

Could you please confirm if you are able to successfully install the genome when rsync is TRUE and bash is false? Thanks!

**Comment by mattjmeier** [comment]
Thanks for the reply. I think I tried that combination at some point but just to confirm:


```
SigProfilerMatrixGeneratorR::install("GRCh38", rsync=TRUE, bash=FALSE)
Beginning installation. This may take up to 40 minutes to complete.
Direct download for RSYNC is not yet supported
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
SystemExit
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\NNNNNNN\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 913, in install
    sys.exit()
SystemExit

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─genInstall$install(genome, custom, rsync, bash, ftp)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 ```

I can't quite remember why, but I was thinking that when it did successfully download the `tar.gz` file, it wasn't getting extracted to the right location.

Happy to hear any other suggestions!

**Comment by mdbarnesUCSD** [comment]
Okay, it looks like the section of the code for downloading with rsync was not being reached. To resolve this, please set ftp to false. The code entered the [if statement at 859](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/install.py#L859-L913) and it looks like this is the reason for the error.

**Comment by mattjmeier** [comment]
Thank you! Some progress now, but not quite working yet.

I'm not sure if the rsync error below matters or not, because it does seem to proceed past that. But it seems as though it still isn't downloading the chromosome files and putting them where they need to go.

In some of the debug messages there is a mix of forward and backslashes in the file paths. I don't know whether this is just an artifact of how the messages are strung together, or if something internally within python is mixing and matching.

```
>   SigProfilerMatrixGeneratorR::install(project_genome, rsync=TRUE, bash=FALSE, ftp=FALSE)
rsync: on remote machine: -: unknown option
rsync error: syntax or usage error (code 1) at main.c(1769) [server=3.2.6]
Beginning installation. This may take up to 20 minutes to complete.
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  C:\Users\NNNNN\.virtualenvs\DupSeqR\Lib\site-packages\SigProfilerMatrixGenerator
[DEBUG] Chromosome string files found at: C:\Users\NNNNN\.virtualenvs\DupSeqR\Lib\site-packages\SigProfilerMatrixGeneratorreferences/chromosomes/chrom_string/GRCh38/
[DEBUG] Chromosome fasta files found at: C:\Users\NNNNN\.virtualenvs\DupSeqR\Lib\site-packages\SigProfilerMatrixGenerator\references\chromosomes\fasta/GRCh38/
Chromosomes are not currently saved as individual text files for GRCh38. Downloading the files now...
Chromosome fasta files for GRCh38 have been installed. Creating the chromosome string files now...
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\NNNNN\\.virtualenvs\\DupSeqR\\Lib\\site-packages\\SigProfilerMatrixGenerator\\references\\chromosomes\\fasta\\GRCh38\\'
Run `reticulate::py_last_error()` for details.
```

This is last error output:

```
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\NNNNNN\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 1000, in install
    install_chromosomes(genomes, reference_dir, custom, rsync, bash)
  File "C:\Users\NNNNNN\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 573, in install_chromosomes
    save_chrom_strings.save_chrom_strings(genome, custom)
  File "C:\Users\NNNNNN\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\scripts\save_chrom_strings.py", line 41, in save_chrom_strings
    chrom_fasta_files = os.listdir(chrom_fasta_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\NNNNNN\\.virtualenvs\\DupSeqR\\Lib\\site-packages\\SigProfilerMatrixGenerator\\references\\chromosomes\\fasta\\GRCh38\\'

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─genInstall$install(genome, custom, rsync, bash, ftp)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
```

Thanks again, hopefully this is informative.

**Comment by mattjmeier** [comment]
Oh and in case it helps:

![image](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/14365280/c065e925-b6e1-4a0f-8338-b7ff43f2259b)

The GRCh37 and GRCh38 folders shown are both empty.

**Comment by mdbarnesUCSD** [comment]
Okay, thanks I will need to take a closer look at this issue. Could you please provide the version of SigProfilerMatrixGenerator that is being used?

**Comment by mattjmeier** [comment]
Of course:

```
SigProfilerMatrixGenerator       1.2.19
```

Seems to be the latest.

Thank you again for your help!

**Comment by mattjmeier** [comment]
Hello, I was just wondering if there is anything else I might try to troubleshoot this, or if there are any more details I can provide you with.

I tried to create a new virtual environment in case something was wrong with the packages I was working with. Made no difference in my hands though.

**Comment by mdbarnesUCSD** [comment]
Hi, thanks for offering. I had needed to setup a Windows environment to test the code on, but have done this now and see that this is an error that appears because of forward and backslashes on Windows. I will be updating the way these strings are built, and am aiming to have a fix out during next week (after the holiday).

If you are able to download the files from the ftp server, the program is moves the unzipped directory downloaded from the ftp server to the site-packages inside of SigProfilerMatrixGenerator/references/chromosomes/tsb/.

**Comment by mattjmeier** [comment]
Thanks so much for looking into it! Yeah that is really annoying about the slashes. Personally I usually do this kind of work on a linux machine as well, but I'm developing an analysis workflow for people who will mostly be using Windows.

I will see if I can get it to download and unpack directly as well.

Enjoy the holiday!

**Comment by mattjmeier** [comment]
Thanks for the fix!

I hope you still might consider using curl instead of wget (although I am sure there are some reasons wget is better for downloading recursively when that's needed...). The problem is that if I have users without admin rights, they can't install wget. Maybe can find a workaround using something like this: https://github.com/YuLab-SMU/wget

**Comment by mdbarnesUCSD** [comment]
Thanks for the suggestion, this is something that we will look into adding support for. Please reach out if you encounter any issues.

**Comment by mattjmeier** [comment]
FYI - still looks like I'm getting a mix of forward and backslashes in the path construction?

```
SigProfilerMatrixGeneratorR::install(project_genome, rsync=TRUE, bash=FALSE, ftp=FALSE)
rsync: on remote machine: -: unknown option
rsync error: syntax or usage error (code 1) at main.c(1769) [server=3.2.6]
Tool       | Status    
-----------------------
wget       | Installed 
rsync      | Installed 
tar        | Installed 
Beginning installation. This may take up to 20 minutes to complete.
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  C:\Users\NNNNN\Documents\.virtualenvs\DupSeqR\Lib\site-packages\SigProfilerMatrixGenerator
[DEBUG] Chromosome string files found at: C:\Users\NNNNN\Documents\.virtualenvs\DupSeqR\Lib\site-packages\SigProfilerMatrixGeneratorreferences/chromosomes/chrom_string/GRCh38/
[DEBUG] Chromosome fasta files found at: C:\Users\NNNNN\.virtualenvs\DupSeqR\Lib\site-packages\SigProfilerMatrixGenerator\references\chromosomes\fasta/GRCh38/
Chromosomes are not currently saved as individual text files for GRCh38. Downloading the files now...
Chromosome fasta files for GRCh38 have been installed. Creating the chromosome string files now...
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\\NNNNN\\Documents\\.virtualenvs\\DupSeqR\\Lib\\site-packages\\SigProfilerMatrixGenerator\\references\\chromosomes\\fasta\\GRCh38\\'
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\NNNNN\DOCUME~1\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 1011, in install
    install_chromosomes(genomes, reference_dir, custom, rsync, bash)
  File "C:\Users\NNNNN\DOCUME~1\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 573, in install_chromosomes
    save_chrom_strings.save_chrom_strings(genome, custom)
  File "C:\Users\NNNNN\DOCUME~1\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\scripts\save_chrom_strings.py", line 41, in save_chrom_strings
    chrom_fasta_files = os.listdir(chrom_fasta_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\\NNNNN\\Documents\\.virtualenvs\\DupSeqR\\Lib\\site-packages\\SigProfilerMatrixGenerator\\references\\chromosomes\\fasta\\GRCh38\\'

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─genInstall$install(genome, custom, rsync, bash, ftp)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 ```

**Comment by mattjmeier** [comment]
I would think these are the offending lines:

![image](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/14365280/9a53fe87-36ac-4182-9c1c-13998cf41d3f)

**Comment by mdbarnesUCSD** [comment]
Thanks for notifying that these parameters did not work for installing on Windows. Could you please let me know if setting ftp=TRUE works for you?

**Comment by xiaoyaojianghuzai** [comment]
marked ，waiting for upgrade！

**Comment by mattjmeier** [comment]
Thanks again @mdbarnesUCSD . I tried with FTP set to true:

```

>   SigProfilerMatrixGeneratorR::install("GRCh38", rsync=TRUE, bash=FALSE, ftp=TRUE)  
Tool       | Status    
-----------------------
wget       | Installed 
rsync      | Installed 
tar        | Installed 
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  OSError: [WinError 6] The handle is invalid
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\NNNNN\DOCUME~1\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 957, in install
    install_via_ftp(genome, reference_dir, check_sum)
  File "C:\Users\NNNNN\DOCUME~1\VIRTUA~1\DupSeqR\lib\site-packages\SigProfilerMatrixGenerator\install.py", line 839, in install_via_ftp
    subprocess.run(
  File "C:\Users\NNNNN\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\398E0A~1.13\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\NNNNNAppData\Local\R\win-library\4.2\reticulate\python\rpytools\subprocess.py", line 15, in __init__
    return og_Popen__init__(self, *args, **kwargs)
  File "C:\Users\NNNNN\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\398E0A~1.13\lib\subprocess.py", line 829, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\NNNNN\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\398E0A~1.13\lib\subprocess.py", line 1270, in _get_handles
    c2pwrite = _winapi.GetStdHandle(_winapi.STD_OUTPUT_HANDLE)
OSError: [WinError 6] The handle is invalid

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SigProfilerMatrixGeneratorR::install(...)
 2.   └─genInstall$install(genome, custom, rsync, bash, ftp)
 3.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 ```

**Comment by mattjmeier** [comment]
Also just a quick note to say that if one uses a python venv, the `wget.exe` binary can be downloaded and placed in the `Scripts` folder of the venv. This does make it available on the "system path" in that context (even using reticulate), as long as the venv is loaded, and doesn't require admin rights. However, this would require re-distribution of the wget binary, which - while not against the license - is maybe a bit sketchy.

**Comment by mattjmeier** [comment]
> I would think these are the offending lines:
> 
> ![image](https://private-user-images.githubusercontent.com/14365280/287388585-9a53fe87-36ac-4182-9c1c-13998cf41d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTYxNzMsIm5iZiI6MTcwNDM5NTg3MywicGF0aCI6Ii8xNDM2NTI4MC8yODczODg1ODUtOWE1M2ZlODctMzZhYy00MTgyLTljMWMtMTM5OThjZjQxZDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE5MTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MWY5ZDViNGExZmI2M2ZjNTFiZjQ5NDI2ZmNmN2ZlZWQyYTIzOTU2Y2MwOTlkNjU5MjQyYTMyMGNjODFkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NWiY0Zbd7we9sU1UIowDR85DfGiupKankGIcB9O2qKY)

Hello and happy new year,
Did you ever get a chance to look at these lines?

Thanks,
Matt

**Comment by mdbarnesUCSD** [comment]
Hi Matt,

My understanding of the existing code has changed a bit. Rsync is used specifically for installing reference_genomes behind firewalls and uses a section of code for custom genome installation. I would like to leave the both rsync and custom genome installation as it is, but am updating the default installer. I have [added branch i161_pt2](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/tree/i161_pt2) that updates the default installation (ie. parameters are custom=False, rsync=False, bash=True, ftp=True). This updated installation uses ftplib (distributed with python) by default and curl as backup. Could you please let me know if this branch works on your setup?

Thanks!

**Comment by mattjmeier** [comment]
Thanks very much for this follow up! I will test it out as soon as it can and let you know how it goes. Really appreciate your help!
