### ISSUE TITLE
UnicodeDecodeError: when run the examples

### ISSUE THREAD

**Issue by xiaoyaojianghuzai** [AlexandrovLab/SigProfilerMatrixGenerator#164]
when i run the examples 
it return
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
what can i do to solve it . i can't find which py script the package reads csv

**Comment by xiaoyaojianghuzai** [comment]
![image](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/115333382/06facdc0-5c94-4c6f-aea7-9821582f2350)

**Comment by xiaoyaojianghuzai** [comment]
it's in linux

**Comment by mdbarnesUCSD** [comment]
Hi @xiaoyaojianghuzai,

Please provide:
1. The version of SigProfilerMatrixGenerator
2. The commands that were run
3. Any log files

Thanks!

**Comment by xiaoyaojianghuzai** [comment]
1.
![image](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/115333382/7eac92e3-e014-4394-8b1f-a1fbaa7e4583)
2. when run the examples
```
from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen
matrices = matGen.SigProfilerMatrixGeneratorFunc("test", "GRCh37", "/home/sxt/miniconda3/envs/r-reticulate/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37",plot=True, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100)
```
3.the returns are listed
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sxt/miniconda3/envs/r-reticulate/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 1358, in SigProfilerMatrixGeneratorFunc
    snv, indel, skipped, samples = convertIn.convertTxt(
  File "/home/sxt/miniconda3/envs/r-reticulate/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/convert_input_to_simple_files.py", line 472, in convertTxt
    next(f)
  File "/home/sxt/miniconda3/envs/r-reticulate/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by mdbarnesUCSD** [comment]
Hi @xiaoyaojianghuzai,

The third parameter that was passed should be the path to the directory containing your VCF files.

This is what was passed, which is causing the error:
> "/home/sxt/miniconda3/envs/r-reticulate/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37"
