### ISSUE TITLE
Verifying and benchmark installation error

### ISSUE THREAD

**Issue by FWYX** [AlexandrovLab/SigProfilerMatrixGenerator#166]
I encountered some problems when using genInstall.install(‘GRCh37’, rsync = True), please help me figure out how to solve them.
![9fc72f06c005ea5fa327a6f41a30e41](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/61787054/94027848-264d-43ee-9bfa-8ca9c3235060)
![9bc24728c10eba9dcf5a06d3cec4536](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/61787054/976df219-8142-415c-b220-daa72d23dd15)

**Comment by FWYX** [comment]
This picture is relatively clear.
![69f96f3045b801656f2503ae1306c20](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/61787054/ee794cb9-0334-43ba-96fd-25a129e0fc25)

**Comment by FWYX** [comment]
@gipatelli I had the same problem.
![d453965f512d604a76403bb0547a24b](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/assets/61787054/c9d3fcc8-eb1b-41e7-b911-55f69bc5324f)

**Comment by FWYX** [comment]
@mdbarnesUCSD Can you tell me where the program generates this folder: ref_dir/reference/chromosomes/transcripts/GRCh37. Thanks

**Comment by FWYX** [comment]
@gipatelli This should be caused by the bench file not downloading successfully, but I've found that as long as your reference file downloads are complete, this doesn't affect the subsequent analysis. 
You can use this code test. You should modify vcf_path and genome to suit your situation:
project = "BRCA"
genome = "GRCh37"
vcf_path = "/home/wangfeng/miniconda3/envs/Sig_test/lib/python3.12/site-packages/SigProfilerMatrixGenerator/references/vcf_files/BRCA_example/SNV/"
matrices = matGen.SigProfilerMatrixGeneratorFunc(project, genome, vcf_path, exome=False, bed_file=None, chrom_based=False, plot=False, tsb_stat=False, seqInfo=False)

**Comment by gipatelli** [comment]
@FWYX thank you. Can you tell me which file should I edit with the modifications you suggested? 

thank you again

**Comment by FWYX** [comment]
@gipatelli vcf_path should equal "your_python_package_site/SigProfilerMatrixGenerator/references/vcf_files/BRCA_example/SNV/"

**Comment by FWYX** [comment]
> @gipatelli vcf_path should equal "your_python_package_site/SigProfilerMatrixGenerator/references/vcf_files/BRCA_example/SNV/"

There should be a file named BRCA_example_subs_simple.txt.

**Comment by FerriolCalvet** [comment]
Hi!
I also had a similar issue, but I don't fully understand how you solved it.
I managed to solve it by creating the following directory:
`your_python_package_site/SigProfilerMatrixGenerator/references/vcf_files/GRCh38_bench/`

Apparently the tool does not create this directory but once I create it outside of the python execution then I have no issues with the download, and the benchmark can run.
Not sure if this will be helpful, but I am commenting it just in case it is.

**Comment by mdbarnesUCSD** [comment]
Hi,

The v1.1.20 update was for Windows computers, but it seems that there are some issues with some of the paths during the benchmarking phase (after installation). We are looking into fixing this, but for now please use v1.1.19.

**Comment by FWYX** [comment]
@FerriolCalvet Thank you for your suggestion. Actually, I did not solve this problem, but I found that it does not affect the subsequent analysis.

**Comment by FWYX** [comment]
@mdbarnesUCSD Thank you for your reply. I will try the v1.1.19 version.

**Comment by FWYX** [comment]
@mdbarnesUCSD Thank you for your suggestion. I used the v1.1.19 version and was able to run the program correctly.

**Comment by FWYX** [comment]
@gipatelli @FerriolCalvet You can use the v1.1.19 version. I followed the suggestion of mdbarnesUCSD and used the v1.1.19 version to run the program correctly.
