### ISSUE TITLE
EBV reference genome not available

### ISSUE THREAD

**Issue by liangjt6** [AlexandrovLab/SigProfilerMatrixGenerator#172]
Hi, thanks for creating such awesome software, how do I download EBV genome?

I tried
genInstall.install('EBV',  bash=True)
but got error:

INFO - Attempt to download from alexandrovlab failed: 550 Could not get file size.
curl: (78) The file does not exist
ERROR - Curl download failed with error: Command '['curl', '-o', '/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/EBV.tar.gz', 'ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator//EBV.tar.gz']' returned non-zero exit status 78..
ERROR - Curl download failed with error: Command '['curl', '-o', '/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/EBV.tar.gz', 'ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator//EBV.tar.gz']' returned non-zero exit status 78.
INFO - Attempt to download from sanger failed: 550 EBV.tar.gz: No such file or directory
curl: (78) The file does not exist
ERROR - Curl download failed with error: Command '['curl', '-o', '/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/EBV.tar.gz', 'ftp://ngs.sanger.ac.uk/scratch/project/mutographs/SigProf//EBV.tar.gz']' returned non-zero exit status 78..
ERROR - Curl download failed with error: Command '['curl', '-o', '/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/EBV.tar.gz', 'ftp://ngs.sanger.ac.uk/scratch/project/mutographs/SigProf//EBV.tar.gz']' returned non-zero exit status 78.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/install.py", line 513, in install
    genome_manager.download_genome(genome)
  File "/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/reference_genome_manager.py", line 379, in download_genome
    self._unzip_file(local_filepath)
  File "/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/reference_genome_manager.py", line 554, in _unzip_file
    with tarfile.open(file_path, "r:gz") as tar:
  File "/usr/lib/python3.9/tarfile.py", line 1629, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.9/tarfile.py", line 1675, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/EBV.tar.gz'

using the latest SigProfilerMatrixGenerator
Version: 1.2.22
Thanks in advanced

**Comment by mdbarnesUCSD** [comment]
Hi @liangjt6,

The ebv file is not currently present on the ftp server. We will be looking into this.

Thanks

**Comment by mdbarnesUCSD** [comment]
Hi @liangjt6,

Please update to SigProfilerMatrixGenerator v1.2.24 and try installing again. Please reach out if you encounter any issues.
