### ISSUE TITLE
Issue installing reference genome

### ISSUE THREAD

**Issue by niyati1211** [AlexandrovLab/SigProfilerMatrixGenerator#176]
I am getting the following errors when installing the GRCh38 reference genome using the command (`genInstall.install('GRCh38', rsync=False, bash=True`)

```
Tool       | Installed 
curl       | True      
wget       | True      
rsync      | True      
INFO - Downloading GRCh38...
INFO - Attempt to download from alexandrovlab failed: [Errno 104] Connection reset by peer

INFO - Attempt to download from sanger failed: [Errno 104] Connection reset by peer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
FileNotFoundError: [Errno 2] No such file or directory: '/SigProfiler/lib/python3.8/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh38.tar.gz'
```

I tried to install the "GRCh38.tar.gz" manually with the command:
`wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz`. This also gives me an error:

```
--2024-02-26 13:36:07--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz
  (try:20) => ‘GRCh38.tar.gz’
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... connected.
Error in server response. Closing.
Giving up.
```

Any advice on how to install the reference genome will be appreciated! Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @niyati1211,

I see that you have closed this issue so hopefully you have found a solution. Could you please provide some insight into what the solution was, even if it was just running the download again?

Thanks!

**Comment by niyati1211** [comment]
Hi Mark,

I actually closed the issue since I noticed this error was posted multiple times by other users, and I decided to first troubleshoot myself using the approaches that were previously suggested. Though, I am still getting errors.

Solution 1: “pip install SigProfilerMatrixGenerator==1.2.19”
I installed this version and ran the command: genInstall.install('GRCh38', rsync=False, bash=True). It seemed to be working at first.

Error:
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /gpfs/data/pierce-lab/Niyati/miniconda3/envs/SigProfiler/lib/python3.8/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh38.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

Solution 2: genInstall.install('GRCh38', rsync=True, bash=True)
Error:
Beginning installation. This may take up to 40 minutes to complete.
Direct download for RSYNC is not yet supported.

So, in the end I may need to open again (I apologize for the confusion!). Any help will be greatly appreciated.


From: mdbarnesUCSD ***@***.***>
Date: Wednesday, February 28, 2024 at 2:45 PM
To: AlexandrovLab/SigProfilerMatrixGenerator ***@***.***>
Cc: Niyati Jain ***@***.***>, Mention ***@***.***>
Subject: Re: [AlexandrovLab/SigProfilerMatrixGenerator] Issue installing reference genome (Issue #176)

Hi @niyati1211<https://github.com/niyati1211>,

I see that you have closed this issue so hopefully you have found a solution. Could you please provide some insight into what the solution was, even if it was just running the download again?

Thanks!

**Comment by mdbarnesUCSD** [comment]
Thanks for reaching back out. I think you are likely downloading from behind a firewall, and this is blocking the installation. Here is a solution that may work for you.

If you can download the reference genome from our FTP server on a computer (that is not blocked by a firewall) and then transfer it to the computer that you are attempting to run the program on.

Download one of the reference genomes by running:

```bash
wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz

```
Then install the reference genome into your environment using python:
```python3
from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('GRCh37', offline_files_path='path/to/directory/containing/GRCh38.tar.gz')
```

Please let me know if this works for you.

**Comment by niyati1211** [comment]
Thank you so much. It works for me now!

**Comment by mdbarnesUCSD** [comment]
Great! Please reach out if you have any other issues.

**Comment by sainadfensi** [comment]
Hi,

I'm facing the same issue with downloading the reference. I wonder how it was solved? 

`wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz
--2024-09-20 08:01:10--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz
           => ‘GRCh38.tar.gz’
Resolving alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)... 132.249.225.8
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|132.249.225.8|:21... connected.
Logging in as anonymous ...
Login incorrect.`

**Comment by DittmanC** [comment]
> Thanks for reaching back out. I think you are likely downloading from behind a firewall, and this is blocking the installation. Here is a solution that may work for you.
> 
> If you can download the reference genome from our FTP server on a computer (that is not blocked by a firewall) and then transfer it to the computer that you are attempting to run the program on.
> 
> 1. Download one of the reference genomes by running:
> 
> wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz
> 2. Transfer the file to the computer that you are attempting to run the program on.
> 3. Then install the reference genome into your environment using python:
> 
> from SigProfilerMatrixGenerator import install as genInstall
> genInstall.install('GRCh38', offline_files_path='path/to/directory/containing/GRCh38.tar.gz')
> Please let me know if this works for you.

wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz
It is not working for me
