### ISSUE TITLE
error when using maf file as input

### ISSUE THREAD

**Issue by Sumithrasank** [AlexandrovLab/SigProfilerMatrixGenerator#18]
I tried to give a maf file which has all my samples and mutations to SigProfilerMatrixGeneratorR.  The exact command is matrices <- SigProfilerMatrixGeneratorR("WUMDANY_sigprofiler", "GRCh37", "~/Desktop/WUMDANY_sigprofiler/", plot=T, exome=F, bed_file=NULL, chrom_based=F, tsb_stat=F, seqInfo=F, cushion=100)
But I get an error, 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: list index out of range

**Comment by ebergstr** [comment]
Can you please provide a few lines from your input along with the .out and .err files located in the [your_project]/logs/ directory?

**Comment by ebergstr** [comment]
If you are still having issues, feel free to email me the log input files at ebergstr@eng.ucsd.edu.
