### ISSUE TITLE
SigProfilerMatrixGenerator 1.2.26 is still broken: binomtest does not take a parameter "x"

### ISSUE THREAD

**Issue by toddajohnson** [AlexandrovLab/SigProfilerMatrixGenerator#181]
I just installed and ran SigProfilerMatrixGenerator 1.2.26, and it fails with an error that binomtest does not take a parameter _x_. The points in MutationMatrixGenerator.py all use binomtest(x=.  According to https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binomtest.html, binomtest takes a parameter _k_  for the number of successes.

**Comment by mdbarnesUCSD** [comment]
Hi @toddajohnson,

Thanks for filling out and issue. Apologies for the oversight with the v1.2.26 update. We will include a patch for this in the next update.

Thanks again!
