### ISSUE TITLE
Should the copy number segments be filtered before COPY NUMBER MATRIX GENERATION?

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerMatrixGenerator#182]
Hi,

I would like to run de novo extraction for copy number from a cancer cohort that contains both male and female. Should the copy number segments of chrX and chrY be filtered before COPY NUMBER MATRIX GENERATION?  I have tried to find the processing details on the paper "Signatures of copy number alterations in human cancer", but got little.

**Comment by azhark2** [comment]
Hi,

The copy number matrix generation occurs downstream of the copy number calling itself. Whether chrX and chrY should be filtered depends on the biological question and is at the users discretion, and must be done at the copy number calling step, prior to matrix generation.
