### ISSUE TITLE
An IndexError with generating the mutational matrix

### ISSUE THREAD

**Issue by Xinwen1206** [AlexandrovLab/SigProfilerMatrixGenerator#185]
I got this error when I run this function in R. Do you know why it comes from and how I can address it?

Running SigProfilerMatrixGeneratorR...
Starting matrix generation for SNVs and DINUCs...
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  IndexError: index out of range

It seems come from this code: catalogue_generator_single at MutationMatrixGenerator.py#451
for l in range(start1 + 1, start2, 1):
                          if l - 1 < len(chrom_string):

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @Xinwen1206,

Could you please provide the full list of commands that you used to run the code? Also, what input are you using?

Thanks!

**Comment by Xinwen1206** [comment]
Hi @mdbarnesUCSD,

Thanks so much for your reply! I found that the error was caused by using the wrong genome. Once I corrected it, the error was resolved.
