### ISSUE TITLE
EBV reference not installable

### ISSUE THREAD

**Issue by Saranya-Balachandran** [AlexandrovLab/SigProfilerMatrixGenerator#186]
Dear team,
Thank you for the tool.
![Screenshot 2024-07-17 at 13 45 52](https://github.com/user-attachments/assets/eb0f0e89-baf5-4e75-bff0-daef1a7ff142)
Unable to install EBV reference genome. 
I would also like to know if I can combine 2 genomes, grch38 and ebv for the matrix generation?

Thanks

**Comment by mdbarnesUCSD** [comment]
Hi @Saranya-Balachandran,

Thanks for reaching out. Please use "ebv" when you specify the genome and matrix generation is for only one genome type at a time.
