### ISSUE TITLE
skip all dot ('.) files' 

### ISSUE THREAD

**Issue by stephennfitzgerald** [AlexandrovLab/SigProfilerMatrixGenerator#19]
Hi Erik, would it be possible to skip all dot files in scripts/convert_input_to_simple_files.py ?
At the moment you only skip for .DS_Store

	57 	if file == '.DS_Store':

We have been caught by this  a few times.
Thanks,
S.

**Comment by ebergstr** [comment]
Just added! Thanks for pointing that out.

Best,
Erik
