### ISSUE TITLE
SNV Mode Lacks Output Directory Customisation

### ISSUE THREAD

**Issue by DarioS** [AlexandrovLab/SigProfilerMatrixGenerator#193]
CNV and SV modes have an output directory parameter, but not SNV mode. Moreover, CNV and SV modes **require** a separate output folder. It also creates a folder named `input` and copies all of the VCF files to it, wasting disk space. Needs harmonisation.

**Comment by mdbarnesUCSD** [comment]
Matrix generation for indels, doublet base substitutions, and single base substitution generates files during runs that are used in subsequent downstream analysis by other SigProfiler tools. Introducing a new output directory could disrupt tools that rely on these structures. We will consider changing this behavior in a future release.

In the meantime, a wrapper script could be used to remove the duplicated files and move the results to another location.
