### ISSUE TITLE
Error if Compressed VCFs Input

### ISSUE THREAD

**Issue by DarioS** [AlexandrovLab/SigProfilerMatrixGenerator#194]
However, it works well if all files are first unzipped by `gunzip *gz`.
```python
>>> matGen.SigProfilerMatrixGeneratorFunc("SNV", "GRCh38", "/dski/dario/HeadNeck/shortVariants/cellLines/")
File format not supported
```

**Comment by mdbarnesUCSD** [comment]
Input files are expected to be placed in a directory and be unzipped. Please unzip all input VCF files.
