### ISSUE TITLE
Problem encountered running genome installation inside Singularity container

### ISSUE THREAD

**Issue by Katerina10-cloud** [AlexandrovLab/SigProfilerMatrixGenerator#195]
Hi, I'm getting an issue regarding custom genome installation using the `volume ` argument to provide the location of the directory. The volume  is working within the Docker container, but not within the Singularity . Mounting the singularity image and running the following code:

`singularity run --bind /orfeo:/orfeo/ --disable-cache docker://katiad/sigprofiler:latest`
```
INFO:    Creating SIF file...
INFO:    Converting SIF file to temporary sandbox...
Python 3.12.5 (main, Aug 13 2024, 10:19:35) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('GRCh37', rsync=False, bash=True, volume = "/orfeo/LTS/CDSLab/LT_storage/kdavydzenka/tmp/")
```

I got the following error:

```
Tool       | Installed 
-----------------------
curl       | False     
wget       | True      
rsync      | False     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/SigProfilerMatrixGenerator/install.py", line 489, in install
    os.makedirs(dirs)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.12/site-packages/SigProfilerMatrixGenerator/references/chromosomes/chrom_string'
```
From the error message seems that it doesn't recognize the `volume` argument and looking to download the genome inside the container using default path which has read-only file system.
However, the installation code is working inside the Docker container:

```
(base) katsiarynadavydzenka@cli-10-109-0-124 Desktop % docker run -it katiad/sigprofiler:latest
Python 3.12.5 (main, Aug 13 2024, 10:19:35) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SigProfilerMatrixGenerator import install as genInstall
>>> genInstall.install('GRCh37', rsync=False, bash=True, volume = "/Users/katsiarynadavydzenka/Desktop")
Tool       | Installed 
-----------------------
curl       | False     
wget       | True      
rsync      | False     
INFO - Downloading GRCh37...
Downloading: 100.00% [780.58 MB of 780.58 MB] at 15.24 MB/s
Download complete.
INFO - Downloaded GRCh37 from alexandrovlab using FTP.
INFO - GRCh37 has been successfully installed.
All reference files have been created.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete. 
```

**Comment by mdbarnesUCSD** [comment]
Hi @Katerina10-cloud,

Thanks for reaching out about this. It seems that there is an issue that occurs when running the singularity container interactively. I will have to look into this, but in the meantime could you please confirm that running with exec and the CLI does not produce that same error for you:
singularity exec --bind /orfeo:/orfeo/ --disable-cache docker://katiad/sigprofiler:latest SigProfilerMatrixGenerator install GRCh37 -v /orfeo/LTS/CDSLab/LT_storage/kdavydzenka/tmp/

Thanks!

**Comment by Katerina10-cloud** [comment]
By the way, it would be helpful to have working the genome installation using `singularity run `command, as well as `volume `argument withing python script.  Because in my pipeline I'm going to use both `SigProfilerMatrixGenerator` and `SigProfilerExtractor `tools and apparently the last one is not possible to run from CLI.

**Comment by mdbarnesUCSD** [comment]
Hi @Katerina10-cloud,

I wanted to follow back up about why the command I provided worked while the version you ran in the interactive python session did not. The command I ran installs the reference genome using the CLI and this is different than the legacy install command from _install.py._ The CLI uses the [reference_genome_manager](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/scripts/reference_genome_manager.py#L351) to install reference genome files and was written to be more container friendly.

```
from SigProfilerMatrixGenerator.scripts import reference_genome_manager
rgm = reference_genome_manager.ReferenceGenomeManager("<path_to_volume>")
rgm.download_genome("GRCh37")
```
