### ISSUE TITLE
Incorrect MAF format

### ISSUE THREAD

**Issue by marianaurera** [AlexandrovLab/SigProfilerMatrixGenerator#198]
Hi! 

I've been trying to run `cosmic_fit()` on MAF files that were previously read into R as dataframes, subsetted, and then exported with `write.table(maf_dataframe,input_pathname, sep = "\t", quote = F, na = "")`. However, it always returns 'The given input files do not appear to be in the correct MAF format. Skipping this file:..' for only 6 out of 27 of my files despite all having gone through the same process. I can't see why there would be an issue. May I please have your help on this?

`cosmic_fit()` still returns an output of files that do contain the sample names of the files it supposedly skipped over.

thank you in advance!

**Comment by mdbarnesUCSD** [comment]
Hi @marianaurera,

Could you please review the output and error message file in the logs directory?

**Comment by marianaurera** [comment]
Hi @mdbarnesUCSD thanks so much for your prompt reply. But, I was able to figure out the issue late last night. It turns out the file was expecting the '#Version 2.4' header. I think it would be helpful to add more details about what makes the file format incorrect in future updates. Thanks again!
