### ISSUE TITLE
strandBiasTest_384.txt / strandBiasTest_6144.txt files

### ISSUE THREAD

**Issue by lgpdevtools** [AlexandrovLab/SigProfilerMatrixGenerator#20]
Hello Erik,
I've been analyzing output results and regarding those two produced files => 'strandBiasTest_384.txt' & 'strandBiasTest_6144.txt', the number of lines / mut. sig. (96 and 1536) differs from their labels. Are them related or nothing at all?
Thanks.

**Comment by ebergstr** [comment]
These are independent files/tests, therefore, they are not guaranteed to have the same number of lines. Additionally, this feature has been removed and is currently not supported.
