### ISSUE TITLE
Generating mutation matrix for single cells 

### ISSUE THREAD

**Issue by vanshikabidhan** [AlexandrovLab/SigProfilerMatrixGenerator#204]
Hello, 

Thank you for developing the tool. I am trying to create a mutation matrix using single cell (targeted) data, to eventually analyse gene-specific signatures for my gene of interest. I have around ~30,000 vcfs for each single cell. I also have multisample vcfs, but the tool doesn't take them as an input. I have filtered the vcfs for my gene of interest. I ran a test script with 100 vcfs, and it did work well, however, as I want to eventually run it for all 30k cells, I wanted to ask whether the tool can handle this? The script has been running for more than 90 hours now. Do you have any suggestions on how should I move forward with this? 

Thank you, 
Vanshika

**Comment by mdbarnesUCSD** [comment]
Hi @vanshikabidhan,

It is possible that you are running out of memory when generating these matrices. You do not need to run all 30,000 samples at once. Instead you could split your samples over multiple runs and then merge the matrices together afterwards. Hope this helps.

**Comment by mdbarnesUCSD** [comment]
Please reach out if encounter any additional issues or have any questions.

**Comment by vanshikabidhan** [comment]
That worked! Thanks.
