### ISSUE TITLE
Interpretation of strand + and - into svclass values is incorrect

### ISSUE THREAD

**Issue by nnordborg** [AlexandrovLab/SigProfilerMatrixGenerator#205]
Is the current implementation (SVMatrixGenerator.py line 1112 to 1123) of assigning an "svclass" value based on the "strand1" and "strand2" columns in a bedpe file correct? 

https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/98ead16c3be5f94ca8cf397f883883ee4b6e0537/SigProfilerMatrixGenerator/scripts/SVMatrixGenerator.py#L1112

I think "+-" should be "deletion", "-+" should be "tandem-duplication" and "++"/"--" should be inversion and this is also what the documentation of Viola-SV indicates. See https://viola-sv.readthedocs.io/en/1.0.x-stable-doc/userguide/sv_position_specification.html

**Comment by azhark2** [comment]
The current implementation is correct as the strand convention is based on BRASS output, as stated in the documentation 
("strand1" & "strand2 (BRASS convention)". See here for details: https://github.com/cancerit/BRASS.
This is why the foolproof option of providing the exact annotation (e.g deletion) is there, as different SV callers can have different strand conventions.

**Comment by nnordborg** [comment]
Ok, I knew that the VCF formats differ a lot but not that there were different conventions for the bedpe format. It was not easy to find any documentation about the bedpe format and interpretation of the strand column and Viola-SV doesn't mention BRASS. Can you add a link to https://github.com/cancerit/BRASS/wiki/BEDPE in the documentation?

**Comment by azhark2** [comment]
Sure, I will add it to the documentation. Yes, it’s confusing and it’s not
easy to find information on the strand conventions, and now there is a
plethora of different SV callers. Let me know if you have any other
questions!
