### ISSUE TITLE
wget: Error in server response, closing control connection

### ISSUE THREAD

**Issue by gsteinhardt** [AlexandrovLab/SigProfilerMatrixGenerator#21]
The following produced an error with wget:

_from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('GRCh37')_

I think the connection to ngs.sanger.ac.uk/* for the installation of GRCH37 is down. To check:

_wget -r -l1 -c -nc --no-parent -nd -P . ftp://ngs.sanger.ac.uk/scratch/project/mutographs/SigProf/GRCh37.tar.gz 2
--2019-11-22 15:26:09--  ftp://ngs.sanger.ac.uk/scratch/project/mutographs/SigProf/GRCh37.tar.gz
           => `./.listing'
Resolving ngs.sanger.ac.uk... 193.62.203.79
Connecting to ngs.sanger.ac.uk|193.62.203.79|:21... connected.
Logging in as anonymous ... 
Error in server response, closing control connection.
Retrying._

I did a workaround by downloading the genome using a web browser, and i put it in the proper dir: /home/[usr]/.local/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/

i ran genInstall.install('GRCh37') again after placing the genome within /tsb and it seemed to work if anyone else has the same issue with wget.

**Comment by ebergstr** [comment]
Thank you for your report! Our install now first attempts to download the final reference files directly from our own ftp site. If our site is having issues, you should first see "The UCSD ftp site is not responding...pulling from sanger ftp now." This was included to speed up the installation process and to avoid the dependency with the sanger ftp. If you still notice an issue, feel free to reopen an issue.

Best,
Erik
