### ISSUE TITLE
Install.py does not exist

### ISSUE THREAD

**Issue by edawson** [AlexandrovLab/SigProfilerMatrixGenerator#25]
When trying to run SigProfilerMatrixGenerator on a file where the specified reference genome has not been installed, the user receives a message prompting them to install the reference using an install.py script:
```
 python sigprofilermatrixgenerator/generate_matrix.py -m <input>.maf 
The specified genome: GRCh37 has not been installed
Run the following command to install the genome:
	python sigProfilerMatrixGenerator/install.py -g GRCh37
```

However, when running the suggested command, the install.py script is not found:
```
python sigProfilerMatrixGenerator/install.py -g GRCh37
python: can't open file 'sigProfilerMatrixGenerator/install.py': [Errno 2] No such file or directory
```

This looks like an error in the pip install process, as the install.py script does exist in the repo.

It looks like some of the paths are hard-coded as well:
```
 python sigprofilermatrixgenerator/SigProfilerMatrixGenerator/install.py -g GRCh37
Traceback (most recent call last):
  File "sigprofilermatrixgenerator/SigProfilerMatrixGenerator/install.py", line 571, in <module>
    main()
  File "sigprofilermatrixgenerator/SigProfilerMatrixGenerator/install.py", line 516, in main
    os.chdir(first_path + "/sigProfilerMatrixGenerator/")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ericco92/indels_sigprof_1.0.3_2020FEB20/sigProfilerMatrixGenerator/'
```

**Comment by ebergstr** [comment]
Thank you for your feedback. That exception message is actually from an older version and has now been corrected in v1.1.1. The installation process is no longer callable from main() within the install.py script, therefore, we have corrected that message describing the install command by pointing the user to our GitHub repo/README. Please reference the README for installation instructions.

**Comment by edawson** [comment]
Great, thanks! Is 1.1.1.1 into pypi / pip yet?

**Comment by ebergstr** [comment]
Yes, the pip package has been updated actually to 1.1.2.
