### ISSUE TITLE
Certain MAF files produce no 1bp deletions in matrix

### ISSUE THREAD

**Issue by edawson** [AlexandrovLab/SigProfilerMatrixGenerator#26]
Hi,

   I have several MAF files that have known 1bp deletions. When running SigProfilerMatrixGenerator (and subsequently SigProfilerExtractor), the output matrix has counts of 0 for 1:Del:C:0 or 1:Del:T:0 features across all samples.

Here's an example of a 1bp deletion from my MAF:
```
Unknown 0       broad.mit.edu   37      1       168186704       168186704       +       IGR     DEL    C       C       -
```

Do I need to prepend a reference base to both alleles or otherwise preprocess inputs before running SigProfilerMatrixGenerator? Happy to contribute a script to do so if we can figure out the issue.

**Comment by edawson** [comment]
If it's useful, I've also tried implementing a fix in a counting script I wrote: https://github.com/edawson/presig/blob/64e8951e0fe91cc7d378b694a6b46cc0d7ab0d0c/presig/presig.py#L421

I haven't verified that the counts produced are identical to SigProfilerMatrixGenerator, though that's the goal and I'll correct the unit tests for my repo once we chase this down!

**Comment by ebergstr** [comment]
Hi edawson,

I ran your examples through the code (after adding in pseudo-sample names) and was able to detect/report the mutation within the counts matrices. The example you provided is located at a repeat region of 2 (1:Del:C:2, visually validated on the ensembl genome browser).  Do you have alternate examples of this issue that I can test?

Best,
Erik

**Comment by edawson** [comment]
Hi again,

   Thanks for giving this one a go and sorry for sending a poor example. I'll prepare a better one and send it via email later today. I'll make sure to include a false sample name if that helps!

**Comment by ebergstr** [comment]
This should now be fixed in pip version1.1.7. Thank you for the feedback.
