### ISSUE TITLE
Can't download any supported genomes

### ISSUE THREAD

**Issue by Dagsbio** [AlexandrovLab/SigProfilerMatrixGenerator#27]
Hi, I am attempting to download the human genome before running the tool but this link does not work: https://osf.io/s93d5/wiki/6.%20Currently%20Supported%20Genomes/

Could I just download the human genome from any other sources?

Thank you!

**Comment by ebergstr** [comment]
The genomes are not installable via those links for use with the tool. The links provide the ensembl webpage for reference to the builds. To install the genome, please follow the installation process on the GitHub README or on the installation page on the osf documentation.

**Comment by Dagsbio** [comment]
The problem is every time I try it that way, Im gettint this kind of error:

**>>> genInstall.install('GRCh37', bash=True)**
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /home/david/.local/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

OR

**>>> genInstall.install('GRCh37', rsync=False)**
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /home/david/.local/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

**Comment by jchenpku** [comment]
I had exact the same problem, have you gotten around of this error?

**Comment by Dagsbio** [comment]
to be fair I ended up using other tools

**Comment by ebergstr** [comment]
We have observed this issue when users attempt to download on a cluster or machine that has a firewall in place (and/or wget commands to ftp sites are not approved). There are two alternative approaches we recommend: 1) Install using ftp=False 2) Install the relevant genomes on your local machine/computer and then you can upload the entire site-package directly to your cluster.

**Comment by jchenpku** [comment]
Tested it on a VPS, indeed it was caused by the firewall. Thanks
