### ISSUE TITLE
Issues when installing genomes

### ISSUE THREAD

**Issue by Dagsbio** [AlexandrovLab/SigProfilerMatrixGenerator#28]
Hi, 
I have tried both ways of installing genomes, but I can't make it work. This is what I get when I try it:

>>> genInstall.install('GRCh37', bash=True)
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /home/david/.local/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

and

>>> genInstall.install('GRCh37', rsync=False)
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /home/david/.local/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

Do you think I am missing something here?

Thank you!

**Comment by ebergstr** [comment]
Hi,

Is there a firewall on the cluster that you are using? We have experienced issues in the past with wget not working under certain security conditions. To work around this, we provide the RSYNC option: genInstall.install('GRCh37', rsync=True, ftp=False)

**Comment by Dagsbio** [comment]
Fantastic, that finally worked!
