### ISSUE TITLE
Error due to reference file corrupted

### ISSUE THREAD

**Issue by Dagsbio** [AlexandrovLab/SigProfilerMatrixGenerator#29]
"The transcriptional reference data appears to be corrupted. Please reinstall the GRCh38 genome"

Im getting that error after a  list of not matching md5sums .

Do you think is there any way to solve this?

Is there any way I can donwload it manually and keep moving?

**Comment by Dagsbio** [comment]
Forgot to tell you before, but I have tried this many times so I don't think is a connection problem or anything like that.

Thank you.

**Comment by ebergstr** [comment]
You should be able to download the genome directly from ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz, using the following command:

bash -c ' wget -r -l1 -c -nc --no-parent -nd -P  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh38.tar.gz'

Once you have downloaded the file, you can unzip it into the following path:
[path_to_your_python_packages]/SigProfilerMatrixGenerator/references/chromosomes/tsb/

Doing this should allow you to circumvent the install script.
