### ISSUE TITLE
What is the point of this software

### ISSUE THREAD

**Issue by MaryGoAround** [AlexandrovLab/SigProfilerMatrixGenerator#30]
Sorry

I have a big confusion: Can't I directly use `SigProfilerExtractor` to get de novo found signatures or I must use `SigProfilerMatrixGenerator` as a mediate step for `SigProfilerExtractor`?

For running `SigProfilerExtractor`, I had provided my mutations like below for each sample individually as .vcf like below

```
2	81901396	LP6005500-DNA_D03	-	T
4	133567287	LP6005500-DNA_D03	CACCATGAATCTTAGACTTTATTATTGCTTGGTGC	-
X	87420176	LP6005500-DNA_D03	-	T
8	116029769	LP6005500-DNA_D03	TGTC	-
9	92713767	LP6005500-DNA_D03	T	-
4	150842718	LP6005500-DNA_D03	A	-
10	76559024	LP6005500-DNA_D03	-	AAAT
14	98590319	LP6005500-DNA_D03	-	TTTG

```

But SBS , DBS and ID output folders are empty 

So you think I must use `SigProfilerMatrixGenerator` before using `SigProfilerExtractor`?

What is the point of `SigProfilerMatrixGenerator`?

**Comment by ebergstr** [comment]
All of our SigProfiler tools cross talk with one another. The extractor relies upon the output from the matrix generator, therefore, if vcf files are provided, the extractor will automatically call upon the matrix generator. If you have not done so already, I suggest updating both tools and rerunning your pipeline. If this still presents an issue, we will need more information to debug this issue (contents of log files, commands used to run the tool, etc.). Please reference the extractor page for the proper command when attempting signature extractions from vcf files.

**Comment by beginner984** [comment]
Thank you

Without `SigProfilerMatrixGenerator` , by comments of @mishugeb I could run `SigProfilerExtractor`

Now, can I trust the results or using `SigProfilerMatrixGenerator` is essntial?

**Comment by ebergstr** [comment]
Again, if vcf files are provided by the user, SigProfilerExtractor will call upon the matrix Generator in order to generate matrices for extraction. If you are starting with your own matrices, then the matrix generator is not needed.

**Comment by beginner984** [comment]
Thank you for answering me

I have used my own 96 rows mutational catalogues as input

Sorry, by .vcf you mean in intake vcf directly coming from mutation callers or even in my case where I had summarised each .vcf like below

```
2	81901396	LP6005500-DNA_D03	-	T
4	133567287	LP6005500-DNA_D03	CACCATGAATCTTAGACTTTATTATTGCTTGGTGC	-
X	87420176	LP6005500-DNA_D03	-	T
8	116029769	LP6005500-DNA_D03	TGTC	-
9	92713767	LP6005500-DNA_D03	T	-
4	150842718	LP6005500-DNA_D03	A	-
10	76559024	LP6005500-DNA_D03	-	AAAT
14	98590319	LP6005500-DNA_D03	-	TTTG

```
