### ISSUE TITLE
Phasing information in VCF files

### ISSUE THREAD

**Issue by dalibor49** [AlexandrovLab/SigProfilerMatrixGenerator#31]
Hello,

when using SigProfilerMatrixGenerator to parse VCF files following case is encountered:
#CHROM	POS	REF	ALT	sample1
chr1	17000	A	C	0|1
chr1	17001	A	G	1|0
Here two mutations are on consecutive positions in genome but on different chromosome pair. Still SigProfilerMatrixGenerator counts this as DBS pattern (AA>CG), is this expected behaviour, should this be considered a DBS pattern?

Best regards,
Dalibor

**Comment by ebergstr** [comment]
Currently, we do not incorporate phasing information from vcf files, so these will indeed appear as DBSs. We will discuss the potential of incorporating this information in future releases.
