### ISSUE TITLE
Parsing of 3 consecutive mutations

### ISSUE THREAD

**Issue by dalibor49** [AlexandrovLab/SigProfilerMatrixGenerator#32]
Hello,

when 3 consecutive mutations are encountered in VCF, SigProfilerMatrixGenerator will extract 3 SBS and 2 DBS mutational patterns from those 3 mutations. Is this expected behaviour (2 extracted DBS patterns come from "overlaping mutations", is this expected as well)?

Also, same will happen for 4 consecutive mutations(3 DBS and 4 SBS patterns will be extracted).

Best regards,
Dalibor

**Comment by ebergstr** [comment]
Thank you for your comment. We do not currently separate these events, so this behavior is expected.
