### ISSUE TITLE
Fix .gitignore and remove files from version control

### ISSUE THREAD

**Issue by dtip** [AlexandrovLab/SigProfilerMatrixGenerator#33]
Hi,

Your `.gitignore` is currently called `1.gitignore` - you should fix the name because at the moment it's doing nothing.

There are a load of committed `.DS_Store` and `*.pyc` files in this repo - they should not be version controlled!

**Comment by dtip** [comment]
There's also a 33MB tarball in there which probably shouldn't have been committed

**Comment by dtip** [comment]
It gets worse: there are loads of different versions of that tarball in the Git history which is making this repo 1.7GB to download.

You can remove all traces of the tarball from the Git history and drop the size down to 230MB using the below code ([from here](https://stackoverflow.com/questions/1029969/why-is-my-git-repository-so-big))

```
git filter-branch -f --index-filter 'git rm --force --cached --ignore-unmatch dist/*' -- --all
rm -rf .git/refs/original && git reflog expire --expire=now --all && git gc --aggressive && git prune
```

You'll probably need to force push the master branch to get this into the remote.

**Comment by ebergstr** [comment]
Thanks for the close attention to detail. Indeed the .gitignore file was useless this whole time!

**Comment by dtip** [comment]
Hi @ebergstr - I'm not really sure why this issue was closed. All of the `.pyc` and `.DS_Store` files are still committed to the repo. So is the tarball - I'm assuming that means the history is still full of old tarballs as well. Are you planning to fix this?
