### ISSUE TITLE
192 TSB-SBS extraction

### ISSUE THREAD

**Issue by marshelma** [AlexandrovLab/SigProfilerMatrixGenerator#34]
Can I extract 192 transcription strand based mutation type matrix with SigProfilerMatrixGenerator?

**Comment by ebergstr** [comment]
You will need to use SigProfilerExtractor, but yes that option is available. Be sure to use SBS384 or SBS288 as the context. This includes transcribed, untranscribed, non-transcribed, and bi-directionally transcribed regions for SBS384. For SBS288 we remove the bi-directionally transcribed category and add those mutations to the T/Untranscibed categories.
