### ISSUE TITLE
Feature request: Throw an error or warning when the input path is incorrect.

### ISSUE THREAD

**Issue by FreekManders** [AlexandrovLab/SigProfilerMatrixGenerator#41]
Hi,
I accidentally used the tool without using a full path. (I used ~/path/to/directory). However, the tool didn't give any warning or error message that the path was incorrect. It just didn't do anything. It would be nice if the tool threw an error with a descriptive error message, when it can't find the supplied path, so that users know what went wrong.

**Comment by ebergstr** [comment]
Added statement in v1.1.21
