### ISSUE TITLE
rn6 reference does not include MT.txt and it seemes to cause an error for MatrixGenerator.

### ISSUE THREAD

**Issue by monagai** [AlexandrovLab/SigProfilerMatrixGenerator#42]
I solved this problem with placing empty MT.txt.
This is only a report.
(SigProfilerSimulator=1.1.2, rn6=ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/rn6.tar.gz)

**Comment by ebergstr** [comment]
Fixed in v.1.1.21. Note, MT mutations are not currently supported for rn6, but are skipped when generating the matrices.
