### ISSUE TITLE
Missing CNV folder under SigProfilerMatrixGenerator/references

### ISSUE THREAD

**Issue by yingchen69** [AlexandrovLab/SigProfilerMatrixGenerator#43]
Hi,

I just installed SigProfilerMatrixGenerator following instructions. But when I tried to run a test, I got the following error:

    >>> scna.generateCNVMatrix(file_type, input_file, project, output_path)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/yc790/.local/lib/python3.8/site-packages/SigProfilerMatrixGenerator/scripts/CNVMatrixGenerator.py", line 18, in 
    generateCNVMatrix
        with open('SigProfilerMatrixGenerator/references/CNV/CNV_features.tsv') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'SigProfilerMatrixGenerator/references/CNV/CNV_features.tsv'
    >>> 

I checked references folder and there is no CNV folder.

Additionally when I tried to install references for R sessions I got another error:

    > library("SigProfilerMatrixGeneratorR")
    > install('GRCh38', rsync=FALSE, bash=TRUE)
    Error in py_module_import(module, convert = convert) : 
      ModuleNotFoundError: No module named 'SigProfilerMatrixGenerator'
    > traceback()
    4: stop(structure(list(message = "ModuleNotFoundError: No module named 'SigProfilerMatrixGenerator'", 
           call = py_module_import(module, convert = convert), cppstack = structure(list(
               file = "", line = -1L, stack = c("/usr/local/lib/R/site-library/reticulate/libs/reticulate.so(Rcpp::exception::exception(char 
    const*, bool)+0x74) [0x7fea898d7294]", 
               "/usr/local/lib/R/site-library/reticulate/libs/reticulate.so(Rcpp::stop(std::__cxx11::basic_string<char, 
    std::char_traits<char>, std::allocator<char> > const&)+0x29) [0x7fea898c7a66]", 
               "/usr/local/lib/R/site-library/reticulate/libs/reticulate.so(py_module_import(std::__cxx11::basic_string<char, 
    std::char_traits<char>, std::allocator<char> > const&, bool)+0xa5) [0x7fea898e8ea5]", 
               "/usr/local/lib/R/site-library/reticulate/libs/reticulate.so(_reticulate_py_module_import+0xbe) [0x7fea898d346e]", 
               "/usr/lib/R/lib/libR.so(+0xf5b6c) [0x7fea921e0b6c]", 
               "/usr/lib/R/lib/libR.so(+0x13766a) [0x7fea9222266a]", 
               "/usr/lib/R/lib/libR.so(Rf_eval+0x88) [0x7fea92235dd8]", 
               "/usr/lib/R/lib/libR.so(+0x14cc9f) [0x7fea92237c9f]", 
               "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x1a2) [0x7fea92238b92]", 
               "/usr/lib/R/lib/libR.so(+0x13a50e) [0x7fea9222550e]", 
               "/usr/lib/R/lib/libR.so(Rf_eval+0x88) [0x7fea92235dd8]", 
               "/usr/lib/R/lib/libR.so(+0x14cc9f) [0x7fea92237c9f]", 
               "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x1a2) [0x7fea92238b92]", 
               "/usr/lib/R/lib/libR.so(+0x13a50e) [0x7fea9222550e]", 
               "/usr/lib/R/lib/libR.so(Rf_eval+0x88) [0x7fea92235dd8]", 
               "/usr/lib/R/lib/libR.so(+0x14cc9f) [0x7fea92237c9f]", 
               "/usr/lib/R/lib/libR.so(Rf_applyClosure+0x1a2) [0x7fea92238b92]", 
               "/usr/lib/R/lib/libR.so(Rf_eval+0x2af) [0x7fea92235fff]", 
               "/usr/lib/R/lib/libR.so(Rf_ReplIteration+0x202) [0x7fea92269ff2]", 
               "/usr/lib/R/lib/libR.so(+0x17f380) [0x7fea9226a380]", 
               "/usr/lib/R/lib/libR.so(run_Rmainloop+0x50) [0x7fea9226a440]", 
               "/usr/lib/R/bin/exec/R(main+0x1f) [0x55b23511a09f]", 
               "/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fea91f200b3]", 
               "/usr/lib/R/bin/exec/R(_start+0x2e) [0x55b23511a0de]"
               )), class = "Rcpp_stack_trace")), class = c("Rcpp::exception", 
       "C++Error", "error", "condition")))
    3: py_module_import(module, convert = convert)
    2: reticulate::import("SigProfilerMatrixGenerator.install")
    1: install("GRCh38", rsync = FALSE, bash = TRUE)
    > 
Any suggestion?

Thanks a lot for the help!

Ying

**Comment by azhark2** [comment]
Hi,

Sure, happy to help with the first error. Can you please let me know how you installed the tool?

Thanks,
Azhar

**Comment by lalexandrov1018** [comment]
There has been no response for the last week. Ticket close. Please submit another one if issue is not resolved.
