### ISSUE TITLE
offline mode?

### ISSUE THREAD

**Issue by RichardCorbett** [AlexandrovLab/SigProfilerMatrixGenerator#46]
Hi there,
I want to put this code into a container that will be run on a cluster from which the internet will be inaccessible.   Is it possible to build the matrices using a fasta file reference, or perhaps used a stripped down version of the matrix generation that works only for SNVs and Indels?

**Comment by RichardCorbett** [comment]
It may be equally helpful if I could set a path to install the reference information and then point the code to use that path is subsequent runs.  Is this possible?

**Comment by ebergstr** [comment]
If you wish to run the tool on a cluster without an internet connection, I suggest setting the tool up with the desired reference genomes on a machine with internet connection first. Then simply transfer the entirety of the installed package over to your python site-package path within your container. The tool only requires internet for the initial installation. After that, it will use the same path within your site-package directory. Hope that makes sense!
