### ISSUE TITLE
File format not supported

### ISSUE THREAD

**Issue by RichardCorbett** [AlexandrovLab/SigProfilerMatrixGenerator#52]
Hi folks,

I am trying to plot the mutational spectrum of results from a set of variant calls from nanopore data called with claire.

A snapshot of the file looks like this:
```
...
##contig=<ID=GL000225.1,length=211173>
##contig=<ID=GL000192.1,length=547496>
##contig=<ID=NC_001416.1,length=48502>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  GM24385-422
1       584592  .       C       T       1227    .       .       GT:GQ:DP:AF     0/1:1227:43:0.3256
1       846202  .       G       A       953     .       .       GT:GQ:DP:AF     0/1:953:40:0.225
1       858692  .       G       C       946     .       .       GT:GQ:DP:AF     1/1:946:34:0.1176
1       920362  .       C       A       1020    .       .       GT:GQ:DP:AF     0/1:1020:35:0.3143
...
```

When I run SigProfilerMatrixGeneratorFunc using a folder with VCFs like above as my input I get a "File format not supported" error.  The same code seems to work fine on variants called from illumina data using Strelka or Mutect.   Do you see anything incorrect about the VCF format above?

**Comment by ebergstr** [comment]
What's the extension on your file?

**Comment by RichardCorbett** [comment]
My files are named as "422_clair.fp.vcf.gz.g750.snv.vcf" and "442_clair.fp.vcf.gz.g750.snv.vcf"

**Comment by ebergstr** [comment]
This issue is only thrown based upon the file name. I suggest rechecking/renaming your files to ensure you have .vcf as your true extension. Depending on the system, the actual extension may be hidden.

**Comment by RichardCorbett** [comment]
Thanks.  
I got it working now.   I still had errors when using 1.vcf as the name, but it was because my early runs had created the "input", "logs", and "output" folders in the input location.  When I got rid of those files everything works as expected!  Thanks!
