### ISSUE TITLE
Installation of CanFam3.1 failing

### ISSUE THREAD

**Issue by kmegq** [AlexandrovLab/SigProfilerMatrixGenerator#54]
Hello,

I am trying to install the CanFam3.1 reference genome from the list of supported genomes. I was able to successfully install GRCh37 and GRCh38, but when I try to install CanFam3.1, I get:

>>> genInstall.install('CanFam3.1', bash=True)
Beginning installation. This may take up to 40 minutes to complete.
tar (child): /path/lib/python3.7/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/CanFam3.1.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The ensembl ftp site is not currently responding.

I tried various combinations of setting ftp to "False" and rsync to "True," and get the following error saying that CanFam3.1 is not supported:

>>> genInstall.install('CanFam3.1', ftp=False, rsync=True, bash=True)
Beginning installation. This may take up to 20 minutes to complete.
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  /path/lib/python3.7/site-packages/SigProfilerMatrixGenerator
CanFam3.1 is not supported. The following genomes are supported:
GRCh37, GRCh38, mm10

Can you advise me on how to install the CanFam3.1 reference?

Thank you for your help!

Best,
Kate

**Comment by ebergstr** [comment]
Hi Kate,

Please try using 'dog' as your reference genome.

We will update this within the README.
