### ISSUE TITLE
Cannot generate InDel matrix

### ISSUE THREAD

**Issue by marshelma** [AlexandrovLab/SigProfilerMatrixGenerator#57]
The SNV and DNV works fine:

>>> matrices = matGen.SigProfilerMatrixGeneratorFunc("denovoWGS", "mm10", "/home/max2/WD/denovomaf/",plot=False, exome=False, bed_file=None, chrom_based=False, tsb_stat=False, seqInfo=False, cushion=100) 
Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 408.53 seconds.
Starting matrix generation for INDELs...

Then the program just stopped. The log show the following errors

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/max2/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 532, in SigProfilerMatrixGeneratorFunc
    mutation_ID, skipped_mut, total = matGen.catalogue_generator_INDEL_single (mutation_ID, lines, chrom, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, exome, genome, ncbi_chrom, limited_indel, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, seqInfo, gs, log_file)
  File "/home/max2/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py", line 748, in catalogue_generator_INDEL_single
    with open (chrom_path + chrom + '.txt', "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/max2/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/mm10/21.txt'

There are only 20 + XY chromosome in mouse genome and I didn't see any chr21 in my input maf file.

**Comment by mdbarnesUCSD** [comment]
Hi @marshelma,

Thanks for reporting this issue and providing the logs. I will be looking into this and will let you know when I resolve this issue.

Best,
Mark

**Comment by mdbarnesUCSD** [comment]
@marshelma could you please verify that your input MAF file has "mm10" in the genome column?

Thanks!

**Comment by marshelma** [comment]
Thank you so much!

**Comment by marshelma** [comment]
Hi Mark,

The column genome build is GRCm38 which is mm10. Do I need to change it
over to mm10 instead?

Best,
Xiaoxiao

**Comment by mdbarnesUCSD** [comment]
Please change the column to mm10 for now. I will push an update soon so that this does not cause this error.

Thanks,
Mark

**Comment by marshelma** [comment]
Thank you! I will check if it will fix the problem.

Best,
Xiaoxiao

**Comment by marshelma** [comment]
Changing to 'mm10' indeed fix the problem. Thank you so much!

Best,
Xiaoxiao

**Comment by mdbarnesUCSD** [comment]
Great, thanks for letting us know that it worked!
