### ISSUE TITLE
Problem generating custom genome

### ISSUE THREAD

**Issue by IanCodes** [AlexandrovLab/SigProfilerMatrixGenerator#58]
Hi,

I am not able to generate a custom genome for the BALB_cJ reference.

I separated the fasta file containing all chromosomes on to separate files (header '>chr1' etc.) and gzipped them.  Resulting in chr1.txt.gz, etc. (for chr1-19, X and M).   

Transcript information was downloaded from biomart.  The first line of the file:
`MGP_BALBcJ_G0030692     MGP_BALBcJ_T0077445     6       1       45869861        45878905`

I do not have exome coordinates for the genome, so added a dummy BED file containing:
`chr1   1   2`

I ran the following using Python 3.9.2 and SigProfilerMatrixGenerator (ver 1.1.28).
`from SigProfilerMatrixGenerator import install as genInstall`

`genInstall.install("BALB_cJ", custom=True, fastaPath="/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/fasta/separate_chr", transcriptPath="/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/annotation/Transcripts_Ensembl_103_BALB_cJ_v1.txt", exomePath="/mnt/fls01-home01/mqbssid3/scratch/HP_20210412/exome.bed")`

Here is the output:

Beginning installation. This may take up to 20 minutes to complete. 
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  /mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator
The string file has been created for Chromosome: 1 (1/21)  
                                                 10 (2/21)
                                                 18 (3/21)
                                                 14 (4/21)
                                                 X (5/21)
                                                 4 (6/21)
                                                 M (7/21)
                                                 11 (8/21)
                                                 6 (9/21)
                                                 3 (10/21)
                                                 7 (11/21)
                                                 13 (12/21)
                                                 9 (13/21)
                                                 2 (14/21)
                                                 17 (15/21)
                                                 19 (16/21)
                                                 15 (17/21)
                                                 16 (18/21)
                                                 12 (19/21)
                                                 5 (20/21)
                                                 8 (21/21)
Chromosome string files for BALB_cJ have been created. Continuing with installation.
[DEBUG] Chromosome tsb files found at: /mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGeneratorreferences/chromosomes/tsb/BALB_cJ/
The transcriptional reference data for BALB_cJ has not been saved. Creating these files now
Traceback (most recent call last):
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 347, in <module>
    main()
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 344, in main
    save_tsb(chromosome_string_path, transcript_path, output_path)
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 85, in save_tsb
    out.close()
UnboundLocalError: local variable 'out' referenced before assignment
The transcriptional reference data for BALB_cJ has been saved.
All reference files have been created.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete.

HOWEVER: '/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGeneratorreferences/chromosomes/tsb/BALB_cJ/' is empty.  
  
The chromosomes appear to be processed in a temporary location '/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/chrom_string/BALB_cJ/', but is deleted by the program at the end of its run.

Q) Am i doing doing anything obviously wrong?

When I install 'mm39' I only see chromosome files in '/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/mm39/'.  

Q) Is it possible to only install BALB_cJ without annotation or exome data?

Thank you

**Comment by IanCodes** [comment]
Is anyone available to advise on this?

**Comment by mbarnesUCSD** [comment]
Hi @IanCodes,

Thank you for your patience. It does not look like you are doing something obviously wrong. We have not tested the code in python 3.9, but there may be some other issues happening.

Could you please verify that your transcript files still contain data? It is possible that during a previous failed run, the file contents were deleted.

> Q) Is it possible to only install BALB_cJ without annotation or exome data?

You do not need exome data, but you will need annotation data.

If possible I would like to try to reproduce this error. Could you e-mail (mdbarnes@health.ucsd.edu) a chromosome and transcript file for me to test with?

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @IanCodes,

Thank you for your patience. It does not look like you are doing something obviously wrong. We have not tested the code in python 3.9, but there may be some other issues happening.

Could you please verify that your transcript files still contain data? It is possible that during a previous failed run, the file contents were deleted.

Q) Is it possible to only install BALB_cJ without annotation or exome data?
You do not need exome data, but you will need annotation data.

If possible I would like to try to reproduce this error. Could you e-mail (mdbarnes@health.ucsd.edu) a chromosome and transcript file for me to test with?

Thanks!

**Comment by IanCodes** [comment]
Hi @mdbarnesUCSD, 

Thanks for replying.  

I will send on the transcript file.

If I try to run genInstall without the exomePath set I get an error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/install.py", line 436, in install
    shutil.copy(exomePath,ref_dir + "/references/chromosomes/exome/" +  genome + "/")
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/shutil.py", line 417, in copy
    dst = os.path.join(dst, os.path.basename(src))
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Oddly, I ran the genIndex script (as shown in my original post) and got a different error.  As far as i know I have only changed the transcript file to the full genome file.  The output was as before, but the Traceback included the following:

Traceback (most recent call last):
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 346, in <module>
    main()
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 343, in main
    save_tsb(chromosome_string_path, transcript_path, output_path)
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 95, in save_tsb
    with open(transcript_path + files) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/transcripts/BALB_cJ/.nfs0000000443b2e475000001da'

In the [DEBUG] output there is a typo in the path '/SigProfilerMatrixGeneratorreferences/' (missing forward slash between Generator and reference).

Thanks.

**Comment by mdbarnesUCSD** [comment]
Thanks @IanCodes, I am looking into this now.

**Comment by mdbarnesUCSD** [comment]
@IanCodes could please you direct me towards where I could download the fasta file containing all the chromosomes for BALB_cJ?

**Comment by mdbarnesUCSD** [comment]
Hi @IanCodes,

I ran genInstall.install for BALB_cJ with the following parameters as absolute paths:
1. fastaPath set to the directory containing the BALB_cJ files (ie directory containing chr1.txt.gz,..., chrX.txt.gz)
2. Transcript file from Biomart
3. exomePath set to a dummy BED file containing: `chr1 1 2`

The BALB_cJ genome successfully installed without error. Could you please verify that all files being pointed to contain files with non-empty contents? Please let me know if this does not solve your issue.

Thanks!

**Comment by IanCodes** [comment]
I ran it again as you suggested:
from SigProfilerMatrixGenerator import install as genInstall
genInstall.install("BALB_cJ", custom=True, fastaPath="/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/fasta/separate_chr", transcriptPath="/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/annotation/Transcripts_Ensembl_103_BALB_cJ_v1.txt", exomePath="/mnt/fls01-home01/mqbssid3/scratch/HP_20210412/exome.bed")

I can confirm all files contain data.  But I get the following error:
Beginning installation. This may take up to 20 minutes to complete.
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  /mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator
The string file has been created for Chromosome: 1 (1/21)
                                                 10 (2/21)
                                                 18 (3/21)
                                                 14 (4/21)
                                                 X (5/21)
                                                 4 (6/21)
                                                 M (7/21)
                                                 11 (8/21)
                                                 6 (9/21)
                                                 3 (10/21)
                                                 7 (11/21)
                                                 13 (12/21)
                                                 9 (13/21)
                                                 2 (14/21)
                                                 17 (15/21)
                                                 19 (16/21)
                                                 15 (17/21)
                                                 16 (18/21)
                                                 12 (19/21)
                                                 5 (20/21)
                                                 8 (21/21)
Chromosome string files for BALB_cJ have been created. Continuing with installation.
[DEBUG] Chromosome tsb files found at: /mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGeneratorreferences/chromosomes/tsb/BALB_cJ/
The transcriptional reference data for BALB_cJ has not been saved. Creating these files now
Traceback (most recent call last):
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 346, in <module>
    main()
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 343, in main
    save_tsb(chromosome_string_path, transcript_path, output_path)
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 95, in save_tsb
    with open(transcript_path + files) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/transcripts/BALB_cJ/.nfs000000044835439d00023b97'
The transcriptional reference data for BALB_cJ has been saved.
All reference files have been created.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete.

I noticed that the contents of the transcripts directory only contained files for 1-19, and X, not M which is included in the chromosomes directory:
/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/transcripts/BALB_cJ/
10_transcripts.txt  13_transcripts.txt  16_transcripts.txt  19_transcripts.txt  3_transcripts.txt  6_transcripts.txt  9_transcripts.txt
11_transcripts.txt  14_transcripts.txt  17_transcripts.txt  1_transcripts.txt   4_transcripts.txt  7_transcripts.txt  X_transcripts.txt
12_transcripts.txt  15_transcripts.txt  18_transcripts.txt  2_transcripts.txt   5_transcripts.txt  8_transcripts.txt

/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/fasta/separate_chr
chr10.txt.gz  chr12.txt.gz  chr14.txt.gz  chr16.txt.gz  chr18.txt.gz  chr1.txt.gz  chr3.txt.gz  chr5.txt.gz  chr7.txt.gz  chr9.txt.gz  chrX.txt.gz
chr11.txt.gz  chr13.txt.gz  chr15.txt.gz  chr17.txt.gz  chr19.txt.gz  chr2.txt.gz  chr4.txt.gz  chr6.txt.gz  chr8.txt.gz  chrM.txt.gz

I reran the command again with a new chromosome directory without chrM, but it failed with the same error (different .nfs**** number).

My version of Python is:
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46)

**Comment by mdbarnesUCSD** [comment]
Great, thanks!

We have updated the package to ignore hidden files. Please update the package and let us know if you are still experiencing the error.

**Comment by IanCodes** [comment]
I have upgraded to 1.1.29.  I am getting a similar error, with something new at the end "file not found for this species".  I tried using chromosome files with and without 'chr' in the name (chr1 vs 1).

>>> genInstall.install("BALB_cJ", custom=True, fastaPath="/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/fasta/separate_chr", transcriptPath="/mnt/data-sets/bcf/genomeIndexes/BALB_cJ_v1/annotation/Transcripts_Ensembl_103_BALB_cJ_v1.txt", exomePath="/mnt/fls01-home01/mqbssid3/scratch/HP_20210412/exome.bed")

Beginning installation. This may take up to 20 minutes to complete.
[DEBUG] Path to SigProfilerMatrixGenerator used for the install:  /mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator
The string file has been created for Chromosome: 16 (1/21)
                                                 3 (2/21)
                                                 11 (3/21)
                                                 5 (4/21)
                                                 14 (5/21)
                                                 18 (6/21)
                                                 7 (7/21)
                                                 8 (8/21)
                                                 17 (9/21)
                                                 X (10/21)
                                                 13 (11/21)
                                                 4 (12/21)
                                                 2 (13/21)
                                                 12 (14/21)
                                                 15 (15/21)
                                                 10 (16/21)
                                                 6 (17/21)
                                                 9 (18/21)
                                                 M (19/21)
                                                 19 (20/21)
                                                 1 (21/21)
Chromosome string files for BALB_cJ have been created. Continuing with installation.
[DEBUG] Chromosome tsb files found at: /mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGeneratorreferences/chromosomes/tsb/BALB_cJ/
The transcriptional reference data for BALB_cJ has not been saved. Creating these files now
Traceback (most recent call last):
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 347, in <module>
    main()
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 344, in main
    save_tsb(chromosome_string_path, transcript_path, output_path)
  File "/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/save_tsb_192.py", line 96, in save_tsb
    with open(transcript_path + files) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/transcripts/BALB_cJ/.nfs0000000447fa90b700023d37'
The transcriptional reference data for BALB_cJ has been saved.
chromosome  X file not found for this species.
chromosome  Y file not found for this species.
chromosome  1 file not found for this species.
chromosome  2 file not found for this species.
chromosome  3 file not found for this species.
chromosome  4 file not found for this species.
chromosome  5 file not found for this species.
chromosome  6 file not found for this species.
chromosome  7 file not found for this species.
chromosome  8 file not found for this species.
chromosome  9 file not found for this species.
chromosome  10 file not found for this species.
chromosome  11 file not found for this species.
chromosome  12 file not found for this species.
chromosome  13 file not found for this species.
chromosome  14 file not found for this species.
chromosome  15 file not found for this species.
chromosome  16 file not found for this species.
chromosome  17 file not found for this species.
chromosome  18 file not found for this species.
chromosome  19 file not found for this species.
chromosome  20 file not found for this species.
chromosome  21 file not found for this species.
chromosome  22 file not found for this species.
The TSB BED files for BALB_cJ have been saved.
All reference files have been created.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete.

Transcript files are created in '~/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/transcripts/BALB_cJ/'.
10_transcripts.txt  13_transcripts.txt  16_transcripts.txt  19_transcripts.txt  3_transcripts.txt  6_transcripts.txt  9_transcripts.txt
11_transcripts.txt  14_transcripts.txt  17_transcripts.txt  1_transcripts.txt   4_transcripts.txt  7_transcripts.txt  X_transcripts.txt
12_transcripts.txt  15_transcripts.txt  18_transcripts.txt  2_transcripts.txt   5_transcripts.txt  8_transcripts.txt

'/mnt/fls01-home01/mqbssid3/.conda/envs/FreeBayes135/lib/python3.9/site-packages/SigProfilerMatrixGeneratorreferences/chromosomes/tsb/BALB_cJ/' is absent.

Thanks for your help.

**Comment by mdbarnesUCSD** [comment]
We have pushed another update. Please update and let us know if the error is resolved.

Thanks!

**Comment by mdbarnesUCSD** [comment]
@IanCodes please open this issue again if you are still encountering an issue.
