### ISSUE TITLE
Changing reference folder path

### ISSUE THREAD

**Issue by af8** [AlexandrovLab/SigProfilerMatrixGenerator#60]
Hi,

I am building a docker image based on python 3.8 to run `sigproSS`. All software components are installed in `/usr/local` but I would like reference files to be kept outside the docker image (meaning not under `/usr/local` but rather on shared storage system). Is there an easy a way to do this ? 

I am reading the docs and the code but I am not sure it is possible at this time.

Thanks for your help,
Anthony

**Comment by ebergstr** [comment]
Hi Anthony,

Currently, this feature does not exist as the reference genomes are installed as a piece of the python package itself. These reference paths are then used for our subsequent tools and pipelines. However, we see how this may serve as a useful addition to the tool/suite of tools, which we may incorporate in a future release. 

Thanks for the feedback!
