### ISSUE TITLE
more of a question: what is the source of transcribed stand bias reference bed file from?

### ISSUE THREAD

**Issue by ipstone** [AlexandrovLab/SigProfilerMatrixGenerator#61]
Hello, thank you for this nice tool doing a beautiful and comprehensive mutational signature work!
One quick question for the logic in determining the strand bias: I notice the logic is done by using the
     `references/chromosomes/tsb_BED`

I am wondering what is the source of this BED file - is there a reference paper or link for this tsb related bed file?

Thanks!
Isaac

**Comment by ebergstr** [comment]
These files are generated using all protein coding regions of a given genome using the strand coordination of each gene (reference vs. non-reference strand). For the majority of the default reference genomes, this information is downloaded from ENSEMBL's biomart. SigProfilerMatrixGenerator then encodes the information in these BED files into the reference genomes for efficient queries (found under references/chromosome/tsb/ once installed).

**Comment by ipstone** [comment]
Thank you @ebergstr so much for the answer. I was looking at some greater details of the genome/transcript, however, some transcripts I found from some data source (https://www.gencodegenes.org/human/release_19.html ), contains transcripts that are not included in the SigProfilerMatrixGenerator bed files, such as:
`ENST00000456328.2       chr1    +       11868   14409`

This finer detail could impact interpretation of the data (as some regions may be or not be included when considering strand bias etc.).

It would be really helpful to know the exact source file for the bed file - I was looking at the biomart website, but couldn't find the source.

Thanks a lot!
