### ISSUE TITLE
Reason for skipped ID mutations in *.out log file?

### ISSUE THREAD

**Issue by IanCodes** [AlexandrovLab/SigProfilerMatrixGenerator#62]
Please can you explain why a large number of ID variants are being skipped.

About 65,000 ID variants are being skipped.  The VCF files are generated by Freebayes v1.3.5.  Is there something about the format that is not compatible with SignalProfile.  The problem appears to be alternate alleles; all the error appear like the following:

The mutation contains bases that are not recognized. Skipping this mutation: 1 3050706 TGGGGGGGGGTAT TGGGGGGGGGGTAT,TGGGGGGGGGGTAC
The mutation contains bases that are not recognized. Skipping this mutation: 1 3073863 CGGGGGGGGGGGGTTCA CGGGGGGGTTCA,GGGGGGGGGGGGGTTCA
The mutation contains bases that are not recognized. Skipping this mutation: 1 3099174 TAAAAAAGGGGGG TAAAAAAAGGGGGG,TAAAAAAAGGGGG
The mutation contains bases that are not recognized. Skipping this mutation: 1 3101317 TCTTCC TCTCC,TCTCCC
The mutation contains bases that are not recognized. Skipping this mutation: 1 3129938 GCCCCCCCCCTCCCAT GCCCCCCCCTCCCAT,GCCCCCCACCTCCCAT

Thank you.

**Comment by IanCodes** [comment]
I think I have answered my own question, which is to use:
bcftools norm --multiallelic -both

This splits multiallelic alleles in to separate lines for both SNPs and IDs.

I would still be interested to hear whether this is expected usage of SigProfiler?
Also, all ID variant are reported as >1bp COMP variants.  Would you expect this result?

**Comment by ebergstr** [comment]
Correct, the tool cannot handle multiallelic inputs, which as you discovered, will need to be separated into individual lines. It would be unexpected that all of the indels are >1bp complex variants. This suggests that there may be a compatibility issue with the genome versions or with the format of the indels in the original VCFs.
