### ISSUE TITLE
Some gene/transcript isn't present in the GRCh37 tanscripts bed files

### ISSUE THREAD

**Issue by ipstone** [AlexandrovLab/SigProfilerMatrixGenerator#64]
I noticed for some transcripts, such as :
`ENST00000456328.2       chr1    +       11868   14409`
isn't present in the current GRCh37 transcript bed files.

This potentially would affect results regarding to strand bias mutation signatures etc.

Previously I raise the question in #61 , the answer is very helpful, but if possible, I would love to know the exact source of the transcript bed files, therefore, to compare the results with the GENCODE_V19 I have been using (seems to contain more transcripts https://www.gencodegenes.org/human/release_19.html ).
 
Related, do we purposely exclude the pseudo-genes from the transcript bed files?

Thanks

**Comment by ebergstr** [comment]
We pull only the protein coding transcripts as this was the methodology used for the PCAWG analysis. We have alternative versions of several genomes (ie GRCh37_havana) that also include the IG genes.
