### ISSUE TITLE
couldn't download reference genome GRch37.p13

### ISSUE THREAD

**Issue by feiyang555** [AlexandrovLab/SigProfilerMatrixGenerator#66]
Hi,

I am trying this tool, but encounter one error below. So I couldn't download the GRch37 reference genome using the scripts. I also tried to download this reference genome from ENSEMBLE website, but it also don't work.  It seems the problem of ENSEMBLE which doesn't response. Will it be a problem if I use GRch37.p13 version, but not the same one you mentioned in the website? 

### error 
--2021-06-19 20:49:10--  ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz
           => ‘/scratch/90days/uqfyang2/signature/python_3.8.2_packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/.listing’
Resolving alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)... 198.202.90.117
Connecting to alexandrovlab-ftp.ucsd.edu (alexandrovlab-ftp.ucsd.edu)|198.202.90.117|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/tools/SigProfilerMatrixGenerator ... done.
==> PASV ... done.    ==> LIST ... 
Error in server response, closing control connection.
Retrying.

Looking forward to your response

many thanks,

Fei

**Comment by feiyang555** [comment]
I solved this issue by using another computer to download the GRch37.tar.gz manually using (wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz) , and then copy this file to the path [path_to_my_python_packages]/SigProfilerMatrixGenerator/references/chromosomes/tsb/

After that, I unzip the file and used the scripts below. It succeeded! 
$ python3.8
>> from SigProfilerMatrixGenerator import install as genInstall
>> genInstall.install('GRCh37', rsync=True, ftp=False) 

I can say my computer definitely has set up something so I couldn't download GRch37.tar,gz file using my computer.  Please see other three posted issues which I feel useful. 
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/29
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/28
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/13

**Comment by Xiongshizheng** [comment]
Hello, I can't download the file via `genInstall.install('GRCh37',rsync=True,ftpl=False)` because I'm using windows and I can't find the win version of rsync on Anaconda, I was thinking that I can manually extract it to a folder after downloading it via the wget command, thank you very much！！
