### ISSUE TITLE
non-vcf files were picked up

### ISSUE THREAD

**Issue by superjw** [AlexandrovLab/SigProfilerMatrixGenerator#68]
Hi there, 

We encountered an issue while using MatrixGenerator, where other file formats rather than just VCF were picked up by the tool. I am wondering if it is possible to add a file-checker function to allow only VCF files to be processed.

Also, would it be possible to make MatrixGenerator support reading files from compressed.gz files?

Thanks,

Jingwei

**Comment by ebergstr** [comment]
Hi Jingwei,

Can you provide more information as to what type of files were included (extensions/formats?). We accept several other file formats including MAFs, simple text, etc. with extensions (.txt, .maf, .vcf), so this might be why you are seeing this issue. We have a file check to ensure that the provided files adhere to these conventions, and if not, the file should be skipped during the processing step. It is highly recommended to not include other non-mutation files within the main project directory. If you have downstream analysis that needs to be placed in the project directory, I recommend placing these within the output directory. 

Thanks,
Erik

**Comment by superjw** [comment]
Hi Erik,

Thanks for the reply. I think MatrixGenerator picked up some *.log files, potentially some *.o and *.e files, which are in plain text format. Those files were deleted as soon as I identified the problems. I submitted this ticket because I thought other users might experience a similar issue. It has been fixed on my end anyway. So, please do feel free to close this ticket.

Thanks for the suggestions.

Best wishes,

Jingwei
