### ISSUE TITLE
Collapsing sample names when using dots in filenames

### ISSUE THREAD

**Issue by af8** [AlexandrovLab/SigProfilerMatrixGenerator#72]
Hi,

I have a dataset with multiple tumours from a same patient. For instance tumours S1, S2, S3, S4 for patient P08.

I have the following naming nomenclature : `P08.S3.pass.vcf.gz`. 

After SigProfilerSingleSample has run, I end up with only P08 as a sample name. And as a consequence I no longer have data for the four samples and only have one column tagged as `P08`.

I believe this comes from this section of code in `convertVCF` : 
```
	# Iterates through each file 
	for file in files:
		file_name = file.split(".")
		sample = file_name[0]
```

VCF filename is split on the dot character and only the first part is kept leading to some samples loss in the final results.

Would it be possible to improve the handling of vcf filenames so that only the vcf extension is removed and full basename is kept ?

Best,
Anthony

**Comment by mdbarnesUCSD** [comment]
Hi @af8,

We will consider making this update in the future for more sensitive file handling. In the meantime please update the naming nomenclature that you are using to not use the character "." to avoid this issue.

Thanks!
