### ISSUE TITLE
Should reference genome be considered when using CNVMatrixGenerator?

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerMatrixGenerator#77]
Hi. I used the following code to generate CNV48 matrix. I found there was no argument to control the reference genome. I didnt know if the generated CNV48 matrix was correct whether the input ASCAT file was of GRCh38 or GRCh37.
```
$ python3
>>> from SigProfilerMatrixGenerator.scripts import CNVMatrixGenerator as scna
>>> file_type = "ASCAT"
>>> input_file = "/home/lcj/lincj/test/CNVSignature/tmpASCAT.txt"
>>> output_path = "/home/lcj/lincj/test/CNVSignature/CNVSig1130"
>>> project = "test"
>>> scna.generateCNVMatrix(file_type, input_file, project, output_path)
```

**Comment by azhark2** [comment]
The code to generate the matrix does not take into account the reference genome. The reference genome is accounted for in the upstream files you provide, so you will have to check these files to determine whether its GRCh38 or GRCh37.
