### ISSUE TITLE
How to install reference genome

### ISSUE THREAD

**Issue by TomhitsJerry** [AlexandrovLab/SigProfilerMatrixGenerator#79]
![image](https://user-images.githubusercontent.com/22815603/153555724-cc4d7a06-d3dc-484e-a8c6-22099e5da0e4.png)
![image](https://user-images.githubusercontent.com/22815603/153555731-e2706bbc-56cd-484a-b6bc-077ba6cde577.png)
how can I download the 38 reference, it seems the url is missing.Thanks a lot!
both url has tried:
ftp://ngs.sanger.ac.uk/scratch/project/mutographs/SigProf/
ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/[desired_genome].tar.gz

**Comment by TomhitsJerry** [comment]
Thanks！ I tried to access the url using difference web broswer on local computer and finally got it.

**Comment by TomhitsJerry** [comment]
> Hi,
> 
> Are you attempting to install the genome on a computing cluster or non-local infrastructure? If so, you may have a firewall setup that prevents the installation, which is an issue that we've seen in the past. One option is to install the genome on a local computer and then upload the genome to the proper path (~path_to_python_site-packagaes/SigProfilerMatrixGenerator/references/chromosomes/tsb/) on your remote server. A second option is to use our RSYNC functionality (see README), which has been successful in overcoming firewalls in the past.


Thanks！ I tried to access the url using difference web broswer on local computer and finally got it.

**Comment by ebergstr** [comment]
Great! I am closing this issue, but please feel free to open a new issue if you have additional issues.
