### ISSUE TITLE
txt file issue

### ISSUE THREAD

**Issue by dmusachio** [AlexandrovLab/SigProfilerMatrixGenerator#82]
Hi. When I run the example txt file on the SigProfilerMatrixGenerator, it says that the matrix is succesfully generated, but even though there should be a handful of mutations, the plots show that there are 0 mutations. This problem is specific to txt because when I run the sample MAF and VCF, I get a couple of mutations, which is what I would expect. Thank you.

**Comment by mdbarnesUCSD** [comment]
Hi @dmusachio,

Thanks for reaching out. This is an issue with how the y-axis is handled for small counts. I am closing this issue here and opening on [SigProfilerPlotting #19](https://github.com/AlexandrovLab/SigProfilerPlotting/issues/19).

Thanks!
