### ISSUE TITLE
SigProfilerMatrixGenerator Installation Issues in Ubuntu 22.04

### ISSUE THREAD

**Issue by Pravithaks** [AlexandrovLab/SigProfilerMatrixGenerator#83]
When I tried to install using this command below:
"pip install SigProfilerMatrixGenerator"

I recieved the error below:

"error: Failed to download any of the following: ['https://downloads.sourceforge.net/project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz', 'https://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz'].  Please download one of these urls and extract it into 'build/' at the top-level of the source repository.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in ./.local/lib/python3.10/site-packages
  Rolling back uninstall of matplotlib
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/__pycache__/
   from /home/mvrccri/.local/lib/python3.10/site-packages/~_pycache__
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/matplotlib-3.5.2-py3.10-nspkg.pth
   from /tmp/pip-uninstall-gkqsbpwq/matplotlib-3.5.2-py3.10-nspkg.pth
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/matplotlib-3.5.2.dist-info/
   from /home/mvrccri/.local/lib/python3.10/site-packages/~atplotlib-3.5.2.dist-info
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/matplotlib/
   from /home/mvrccri/.local/lib/python3.10/site-packages/~atplotlib
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/axes_grid/
   from /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/~xes_grid
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/axes_grid1/
   from /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/~xes_grid1
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/axisartist/
   from /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/~xisartist
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/
   from /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/~plot3d
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/tests/
   from /home/mvrccri/.local/lib/python3.10/site-packages/mpl_toolkits/~ests
  Moving to /home/mvrccri/.local/lib/python3.10/site-packages/pylab.py
   from /tmp/pip-uninstall-gkqsbpwq/pylab.py
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> matplotlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure."

Please let me know how could I rectify this error.

**Comment by Pravithaks** [comment]
Hai @mdbarnesUCSD,
 
Yes, I already have the python v3.9. But the problem is with pip. There is no pip by default in python 3.9. When I tried to install pip it was installed from python 3.10 automatically. Please share the solution for this issue if you have any links for installing pip from python v3.9. I tried with a few commands, but still installed the same (pip 22.1.2) from python 3.10. 

Kindly help.

**Comment by mdbarnesUCSD** [comment]
I recommend using Anaconda to create a virtual environment with a specified Python version to install and run code:
https://www.anaconda.com/products/distribution#Downloads

Please reach out if you have additional questions.

**Comment by Pravithaks** [comment]
Thanks a lot, @mdbarnesUCSD. Finally, it works. I'm currently installing the reference genome file.
