### ISSUE TITLE
findfont errors 

### ISSUE THREAD

**Issue by MGCarta** [AlexandrovLab/SigProfilerMatrixGenerator#84]
Hi!

Thanks a lot for sharing such a powerful tool! I have two questions about two different topics. 

1. I used the tool to create my own matrix and I got the following errors:

findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Courier New'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.

what about these errors? I have no idea what they might mean. 

2. The second question is about what is printed at the terminal. I attached a screenshot. I am wondering why so many errors? I´m trying to figure out what might have happened but I don't know if my suspicions are correct. 
My VCFs contain many variants with the ALT field empty, could this number of errors be due to this? 
![screenshot](https://user-images.githubusercontent.com/94122893/177307162-5b2000d5-f70b-4153-ac63-a1856e942dea.png)

Any type of suggestions would be really appreciated! Thank you very much. 

Best,
Giulia

**Comment by mdbarnesUCSD** [comment]
Hi @MGCarta,

1. The findfont issue originates from the plot generation, because Matplotlib uses a default font when it can not find the specified font. It may help to remove matplotlib's font cache: https://github.com/matplotlib/matplotlib/issues/13139/

2. Yes, variants with an empty ALT field will throw an error. The rest of the messages are for the following:
The output message has the total number of samples and their total number of SNVS, DINUCs, and INDELs.

Thanks!

**Comment by mdbarnesUCSD** [comment]
The matrix generation step will skip the lines where you have a blank in the ALT, but it will show up as an error. It may be difficult to discern from the error count if any of the errors were significant, so pre-filtering can help with this to ensure there are minimal or no errors.
