### ISSUE TITLE
.all File

### ISSUE THREAD

**Issue by dmusachio** [AlexandrovLab/SigProfilerMatrixGenerator#86]
Hi,

After running the matrixGenerator, I have a file that is called SBS-96 which I believe I can use on the extractor to get signatures. The only issue is that my SBS-96 file is called an ALLfile, and the extractor needs a TXT file. Is there a fix for this/why does the matrix generator generate a ALL file instead of a TXT file when the extractor wants a TXT file and it is impossible to view the ALL file.

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @dmusachio,

The .all file that is produced is a text file and you can use it as input for the extractor. You can open the file and view it with notepad/text edit.
