### ISSUE TITLE
"devtools" Installation error on R

### ISSUE THREAD

**Issue by Pravithaks** [AlexandrovLab/SigProfilerMatrixGenerator#96]
Hello @mdbarnesUCSD,
I'm trying on R. I'm facing issues where installing devtools:

**ERROR: dependency ‘pkgdown’ is not available for package ‘devtools’
* removing ‘/usr/local/lib/R/site-library/devtools’**

The downloaded source packages are in
	‘/tmp/RtmpHMBgvo/downloaded_packages’
Warning messages:
1: In install.packages("devtools", repos = "http://cran.rstudio.com/") :
  installation of package ‘ragg’ had non-zero exit status
2: In install.packages("devtools", repos = "http://cran.rstudio.com/") :
  installation of package ‘pkgdown’ had non-zero exit status
3: In install.packages("devtools", repos = "http://cran.rstudio.com/") :
  installation of package ‘devtools’ had non-zero exit status
> library("devtools")
Error in library("devtools") : there is no package called ‘devtools’
> install.packages("pkgdown")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependency ‘ragg’

**trying URL 'https://cloud.r-project.org/src/contrib/ragg_1.2.2.tar.gz'
Content type 'application/x-gzip' length 424677 bytes (414 KB)
==================================================
downloaded 414 KB

trying URL 'https://cloud.r-project.org/src/contrib/pkgdown_2.0.6.tar.gz'
Content type 'application/x-gzip' length 871371 bytes (850 KB)
==================================================
downloaded 850 KB**

* installing *source* package ‘ragg’ ...
** package ‘ragg’ successfully unpacked and MD5 sums checked
** using staged installation
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-4' found
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-4' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lfreetype -lpng16 -ltiff -lz -ljpeg -lbz2
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find one of freetype2 libpng libtiff-4. Try installing:
 * deb: libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev (Debian, Ubuntu, etc)
 * rpm: freetype-devel libpng-devel libtiff-devel libjpeg-turbo-devel (Fedora, CentOS, RHEL)
 * csw: libfreetype_dev libpng16_dev libtiff_dev libjpeg_dev (Solaris)
If freetype2 libpng libtiff-4 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a freetype2 libpng libtiff-4.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: ft2build.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘ragg’
* removing ‘/usr/local/lib/R/site-library/ragg’
**ERROR: dependency ‘ragg’ is not available for package ‘pkgdown’
* removing ‘/usr/local/lib/R/site-library/pkgdown’**

The downloaded source packages are in
	‘/tmp/RtmpHMBgvo/downloaded_packages’
Warning messages:
1: In install.packages("pkgdown") :
  installation of package ‘ragg’ had non-zero exit status
2: In install.packages("pkgdown") :
  installation of package ‘pkgdown’ had non-zero exit status
> install.packages("ragg")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/ragg_1.2.2.tar.gz'
Content type 'application/x-gzip' length 424677 bytes (414 KB)
==================================================
downloaded 414 KB

* installing *source* package ‘ragg’ ...
** package ‘ragg’ successfully unpacked and MD5 sums checked
** using staged installation
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-4' found
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-4' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lfreetype -lpng16 -ltiff -lz -ljpeg -lbz2
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find one of freetype2 libpng libtiff-4. Try installing:
 * deb: libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev (Debian, Ubuntu, etc)
 * rpm: freetype-devel libpng-devel libtiff-devel libjpeg-turbo-devel (Fedora, CentOS, RHEL)
 * csw: libfreetype_dev libpng16_dev libtiff_dev libjpeg_dev (Solaris)
If freetype2 libpng libtiff-4 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a freetype2 libpng libtiff-4.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: ft2build.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
**ERROR: configuration failed for package ‘ragg’
* removing ‘/usr/local/lib/R/site-library/ragg’**

The downloaded source packages are in
	‘/tmp/RtmpHMBgvo/downloaded_packages’
Warning message:
In install.packages("ragg") :
  installation of package ‘ragg’ had non-zero exit status
> 
I tried to install pkgdown, ragg for devtools dependencies. Unfortunately, it didn't work. Please let me know how to rectify this

**Comment by marcos-diazg** [comment]
Dear @Pravithaks,

The error messages you included look like issues with your R installation and operative system. We strongly recommend using [conda](https://docs.conda.io/en/latest/miniconda.html) to set up your environment with specific python/R versions and your desired dependencies.

In this case, the following lines of code will help you create an R environment containing the devtools package. I hope this helps. I'll proceed to close the ticket since this is not a SigProfilerMatrixGenerator issue, but please let us know if you have further questions.

```
conda create --name my_env -y
conda activate my_env
conda install -c conda-forge r r-devtools -y
```

**Comment by Pravithaks** [comment]
Thanks a lot @marcos-diazg. I got it.
